In [1]:
!pip install git+https://github.com/facebookresearch/ImageBind.git#egg=imagebind
!pip install setuptools<82
!pip install torchcodec

Collecting imagebind
  Cloning https://github.com/facebookresearch/ImageBind.git to /tmp/pip-install-wxy_1rj3/imagebind_9fa7d55c16824f6b90fa375f2786b0da
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/ImageBind.git /tmp/pip-install-wxy_1rj3/imagebind_9fa7d55c16824f6b90fa375f2786b0da
  Resolved https://github.com/facebookresearch/ImageBind.git to commit 53680b02d7e37b19b124fa37bae4b6c98c38f5be
  Preparing metadata (setup.py) ... done
Collecting pytorchvideo@ git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f (from imagebind)
  Cloning https://github.com/facebookresearch/pytorchvideo.git (to revision 6cdc929315aab1b5674b6dcf73b16ec99147735f) to /tmp/pip-install-wxy_1rj3/pytorchvideo_5ae6bb86aed14343b9091649cc5f5eb8
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/pytorchvideo.git /tmp/pip-install-wxy_1rj3/pytorchvideo_5ae6bb86aed14343b9091649cc5f5eb8
  Running command git rev-parse -q --verify 'sha^6cdc929315aab1b5674b6dcf73b16ec99147735f'
  Running command git fetch -q https://github.com/facebookresearch/pytorchvideo.git 6cdc929315aab1b5674b6dcf73b16ec99147735f
  Running command git checkout -q 6cdc929315aab1b5674b6dcf73b16ec99147735f
  Resolved https://github.com/facebookresearch/pytorchvideo.git to commit 6cdc929315aab1b5674b6dcf73b16ec99147735f
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from imagebind) (2.11.0+cu130)
Requirement already satisfied: torchvision in /usr/local/lib/python3.13/dist-packages (from imagebind) (0.26.0+cu130)
Requirement already satisfied: torchaudio in /usr/local/lib/python3.13/dist-packages (from imagebind) (2.11.0+cu130)
Requirement already satisfied: timm in /usr/local/lib/python3.13/dist-packages (from imagebind) (1.0.30)
Collecting ftfy (from imagebind)
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.13/dist-packages (from imagebind) (2025.11.3)
Requirement already satisfied: einops in /usr/local/lib/python3.13/dist-packages (from imagebind) (0.8.2)
Collecting iopath (from imagebind)
  Downloading iopath-0.1.10.tar.gz (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 2.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.19 in /usr/local/lib/python3.13/dist-packages (from imagebind) (2.1.3)
Collecting types-regex (from imagebind)
  Downloading types_regex-2026.9.29.20261017-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (4.2.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (2025.12.0)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (13.0.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (13.0.85)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.13/dist-packages (from ftfy->imagebind) (0.9.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from iopath->imagebind) (4.67.3)
Collecting portalocker (from iopath->imagebind)
  Downloading portalocker-4.4.1-py3-none-any.whl.metadata (10 kB)
Collecting fvcore (from pytorchvideo@ git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f->imagebind)
  Downloading fvcore-0.1.5.post20221221.tar.gz (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 5.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting av (from pytorchvideo@ git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f->imagebind)
  Downloading av-19.0.1-cp312-abi3-manylinux_2_28_x86_64.whl.metadata (5.0 kB)
Collecting parameterized (from pytorchvideo@ git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f->imagebind)
  Downloading parameterized-0.9.0-py2.py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from timm->imagebind) (6.0.3)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.13/dist-packages (from timm->imagebind) (1.33.0)
Requirement already satisfied: safetensors in /usr/local/lib/python3.13/dist-packages (from timm->imagebind) (0.8.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.13/dist-packages (from torchvision->imagebind) (11.3.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch>=2.0.0->imagebind) (1.8.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.0.0->imagebind) (1.3.0)
Collecting yacs>=0.1.6 (from fvcore->pytorchvideo@ git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f->imagebind)
  Downloading yacs-0.1.8-py3-none-any.whl.metadata (639 bytes)
Requirement already satisfied: termcolor>=1.1 in /usr/local/lib/python3.13/dist-packages (from fvcore->pytorchvideo@ git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f->imagebind) (3.3.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.13/dist-packages (from fvcore->pytorchvideo@ git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f->imagebind) (0.9.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub->timm->imagebind) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub->timm->imagebind) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub->timm->imagebind) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub->timm->imagebind) (26.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.0.0->imagebind) (3.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->timm->imagebind) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->timm->imagebind) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->timm->imagebind) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->timm->imagebind) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub->timm->imagebind) (0.16.0)
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 4.8 MB/s eta 0:00:00
Downloading types_regex-2026.9.29.20261017-py3-none-any.whl (11 kB)
Downloading av-19.0.1-cp312-abi3-manylinux_2_28_x86_64.whl (35.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.0/35.0 MB 66.4 MB/s eta 0:00:00
Downloading parameterized-0.9.0-py2.py3-none-any.whl (20 kB)
Downloading portalocker-4.4.1-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.7/129.7 kB 15.3 MB/s eta 0:00:00
Downloading yacs-0.1.8-py3-none-any.whl (14 kB)
Building wheels for collected packages: imagebind, iopath, pytorchvideo, fvcore
  Building wheel for imagebind (setup.py) ... done
  Created wheel for imagebind: filename=imagebind-0.1.0-py3-none-any.whl size=1385668 sha256=78e3f19bccde028969b367da13d3e9c49b18386b4e96c59695f4c7929bd0b104
  Stored in directory: /tmp/pip-ephem-wheel-cache-biq5ag27/wheels/df/9a/83/144b78c3ee619fef44402279f90654d97a8f88b0820a0e6513
  Building wheel for iopath (setup.py) ... done
  Created wheel for iopath: filename=iopath-0.1.10-py3-none-any.whl size=31596 sha256=155460039a9e6b8508ff960b07fe322cda2183b0b7767a7fcd9dc405e2c7357f
  Stored in directory: /root/.cache/pip/wheels/cd/c4/19/776124f304c8d9cb940cb164ec2ad635b42d9d1cf03217506d
  Building wheel for pytorchvideo (setup.py) ... done
  Created wheel for pytorchvideo: filename=pytorchvideo-0.1.5-py3-none-any.whl size=213083 sha256=eaf053ced6505824c1e8310277f7ddb0cfe5bea7401c1d9f4473c6d79045ec09
  Stored in directory: /root/.cache/pip/wheels/a9/5d/d8/e3fc0a70afd48b893197dc1e6381ea58655586cafadce384e5
  Building wheel for fvcore (setup.py) ... done
  Created wheel for fvcore: filename=fvcore-0.1.5.post20221221-py3-none-any.whl size=61447 sha256=2ec81742d70724df27382e103a098fb2beabce98a2d4a14e7064bb3ca2deb620
  Stored in directory: /root/.cache/pip/wheels/6b/1b/9a/9f4843148961a522f56dbeaa5543071ac2389d9a079ec724ab
Successfully built imagebind iopath pytorchvideo fvcore
Installing collected packages: yacs, types-regex, portalocker, parameterized, ftfy, av, iopath, fvcore, pytorchvideo, imagebind
Successfully installed av-19.0.1 ftfy-6.3.1 fvcore-0.1.5.post20221221 imagebind-0.1.0 iopath-0.1.10 parameterized-0.9.0 portalocker-4.4.1 pytorchvideo-0.1.5 types-regex-2026.9.29.20261017 yacs-0.1.8
/bin/bash: line 1: 82: No such file or directory
Requirement already satisfied: torchcodec in /usr/local/lib/python3.13/dist-packages (0.11.0+cu130)

In [2]:
import torch
from imagebind.models.imagebind_model import ImageBindModel
from imagebind.models import imagebind_model
from imagebind import data
from imagebind.models.imagebind_model import ModalityType
import polars as pl
import random

/usr/local/lib/python3.13/dist-packages/imagebind/data.py:10: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [ ]:
manifest_path = "drive/MyDrive/pokemon_data/manifest.jsonl"
metadata_path = "drive/MyDrive/pokemon_data/metadata.jsonl"
device = "cuda:0" # "cpu", "cuda:0"

model = ImageBindModel(
    vision_embed_dim=1280,
    vision_num_blocks=32,
    vision_num_heads=16,
    text_embed_dim=1024,
    text_num_blocks=24,
    text_num_heads=16,
    out_embed_dim=1024,
    audio_drop_path=0.1,
    imu_drop_path=0.7,
)

In [4]:
torch.cuda.get_device_name(0)

'NVIDIA A100-SXM4-40GB'

In [5]:
model.load_state_dict(torch.load("drive/MyDrive/imagebind/.checkpoints/imagebind_huge.pth", weights_only=True))
model.eval()
model.to(device)

ImageBindModel(
  (modality_preprocessors): ModuleDict(
    (vision): RGBDTPreprocessor(
      (cls_token): tensor((1, 1, 1280), requires_grad=True)

      (rgbt_stem): PatchEmbedGeneric(
        (proj): Sequential(
          (0): PadIm2Video()
          (1): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
        )
      )
      (pos_embedding_helper): SpatioTemporalPosEmbeddingHelper(
        (pos_embed): tensor((1, 257, 1280), requires_grad=True)

      )
    )
    (text): TextPreprocessor(
      (pos_embed): tensor((1, 77, 1024), requires_grad=True)
      (mask): tensor((77, 77), requires_grad=False)

      (token_embedding): Embedding(49408, 1024)
    )
    (audio): AudioPreprocessor(
      (cls_token): tensor((1, 1, 768), requires_grad=True)

      (rgbt_stem): PatchEmbedGeneric(
        (proj): Conv2d(1, 768, kernel_size=(16, 16), stride=(10, 10), bias=False)
        (norm_layer): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
      (pos_embedding_helper): SpatioTemporalPosEmbeddingHelper(
        (pos_embed): tensor((1, 229, 768), requires_grad=True)

      )
    )
    (depth): RGBDTPreprocessor(
      (cls_token): tensor((1, 1, 384), requires_grad=True)

      (depth_stem): PatchEmbedGeneric(
        (proj): Conv2d(1, 384, kernel_size=(16, 16), stride=(16, 16), bias=False)
        (norm_layer): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      )
      (pos_embedding_helper): SpatioTemporalPosEmbeddingHelper(
        (pos_embed): tensor((1, 197, 384), requires_grad=True)

      )
    )
    (thermal): ThermalPreprocessor(
      (cls_token): tensor((1, 1, 768), requires_grad=True)

      (rgbt_stem): PatchEmbedGeneric(
        (proj): Conv2d(1, 768, kernel_size=(16, 16), stride=(16, 16), bias=False)
        (norm_layer): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
      (pos_embedding_helper): SpatioTemporalPosEmbeddingHelper(
        (pos_embed): tensor((1, 197, 768), requires_grad=True)

      )
    )
    (imu): IMUPreprocessor(
      (pos_embed): tensor((1, 251, 512), requires_grad=True)
      (cls_token): tensor((1, 1, 512), requires_grad=True)

      (imu_stem): PatchEmbedGeneric(
        (proj): Linear(in_features=48, out_features=512, bias=False)
        (norm_layer): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (modality_trunks): ModuleDict(
    (vision): SimpleTransformer(
      (pre_transformer_layer): Sequential(
        (0): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (1): EinOpsRearrange()
      )
      (blocks): Sequential(
        (0): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (1): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (2): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (3): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (4): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (5): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (6): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (7): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (8): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (9): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (10): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (11): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (12): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (13): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (14): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (15): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (16): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (17): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (18): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (19): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (20): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (21): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (22): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (23): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (24): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (25): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (26): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(

In [ ]:
df = pl.read_ndjson(manifest_path)
metadata_df = pl.read_ndjson(metadata_path)

full_df = df.join(metadata_df.select(pl.exclude("name")), on="dex_num", how="left")

# use_image_flag = [True if i % 2 == 0 else False for i in range(df.shape[0])]
# use_image_flag = random.sample(use_image_flag, len(use_image_flag))
# df = df.with_columns(
#     use_image=pl.Series(use_image_flag)
# )

full_df

shape: (1_000, 5)
┌─────────┬──────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ dex_num ┆ name         ┆ page_title             ┆ image_path             ┆ text                  │
│ ---     ┆ ---          ┆ ---                    ┆ ---                    ┆ ---                   │
│ str     ┆ str          ┆ str                    ┆ str                    ┆ str                   │
╞═════════╪══════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ 0001    ┆ Bulbasaur    ┆ Bulbasaur (Pokémon)    ┆ data/pokemon_data/imag ┆ Bulbasaur is a small, │
│         ┆              ┆                        ┆ es/0001_…              ┆ quadrupe…             │
│ 0002    ┆ Ivysaur      ┆ Ivysaur (Pokémon)      ┆ data/pokemon_data/imag ┆ Ivysaur is a          │
│         ┆              ┆                        ┆ es/0002_…              ┆ quadrupedal amphi…    │
│ 0003    ┆ Venusaur     ┆ Venusaur (Pokémon)     ┆ data/pokemon_data/imag ┆ Venusaur is a squat,  │
│         ┆              ┆                        ┆ es/0003_…              ┆ quadruped…            │
│ 0004    ┆ Charmander   ┆ Charmander (Pokémon)   ┆ data/pokemon_data/imag ┆ Charmander is a       │
│         ┆              ┆                        ┆ es/0004_…              ┆ bipedal, repti…       │
│ 0005    ┆ Charmeleon   ┆ Charmeleon (Pokémon)   ┆ data/pokemon_data/imag ┆ Charmeleon is a       │
│         ┆              ┆                        ┆ es/0005_…              ┆ bipedal, repti…       │
│ …       ┆ …            ┆ …                      ┆ …                      ┆ …                     │
│ 1020    ┆ Gouging Fire ┆ Gouging Fire (Pokémon) ┆ data/pokemon_data/imag ┆ Gouging Fire is a     │
│         ┆              ┆                        ┆ es/1020_…              ┆ massive lion…         │
│ 1021    ┆ Raging Bolt  ┆ Raging Bolt (Pokémon)  ┆ data/pokemon_data/imag ┆ Raging Bolt is a      │
│         ┆              ┆                        ┆ es/1021_…              ┆ massive quadr…        │
│ 1022    ┆ Iron Boulder ┆ Iron Boulder (Pokémon) ┆ data/pokemon_data/imag ┆ Iron Boulder is a     │
│         ┆              ┆                        ┆ es/1022_…              ┆ spherical, b…         │
│ 1023    ┆ Iron Crown   ┆ Iron Crown (Pokémon)   ┆ data/pokemon_data/imag ┆ Iron Crown is an      │
│         ┆              ┆                        ┆ es/1023_…              ┆ armored turqu…        │
│ 1025    ┆ Pecharunt    ┆ Pecharunt (Pokémon)    ┆ data/pokemon_data/imag ┆ Pecharunt is a small  │
│         ┆              ┆                        ┆ es/1025_…              ┆ Pokémon r…            │
└─────────┴──────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [ ]:
# image_df = df.filter(pl.col("use_image") == True)
# text_df = df.filter(pl.col("use_image") == False)

images = ["drive/MyDrive/" + path[5:] for path in full_df["image_path"]]
text = full_df["text"]

images[0]

'drive/MyDrive/pokemon_data/images/0001_Bulbasaur.png'

In [8]:
batch_size = 100

round = 0
all_embeddings = []
for i in range(0, len(images), batch_size):
    print("Round", round)
    cur_input = {
        ModalityType.VISION: data.load_and_transform_vision_data(images[i:i+batch_size], device),
        ModalityType.TEXT: data.load_and_transform_text(text[i:i+batch_size], device),
    }
    print("input loaded")

    with torch.amp.autocast(device, dtype=torch.float16):
        with torch.no_grad():
            embeddings = model(cur_input)

    print(embeddings)
    print()
    all_embeddings.append(embeddings)
    round += 1

Round 0
input loaded
{'vision': tensor([[ 0.0096,  0.0426,  0.0304,  ...,  0.0097, -0.0120,  0.0124],
        [ 0.0096,  0.0439,  0.0311,  ...,  0.0015, -0.0042,  0.0233],
        [ 0.0191,  0.0308,  0.0378,  ...,  0.0053, -0.0263,  0.0048],
        ...,
        [ 0.0304,  0.0396,  0.0382,  ..., -0.0067, -0.0013, -0.0002],
        [ 0.0357,  0.0291,  0.0392,  ..., -0.0172,  0.0083,  0.0047],
        [ 0.0270,  0.0211,  0.0233,  ..., -0.0536,  0.0057,  0.0158]],
       device='cuda:0'), 'text': tensor([[ 0.4884,  2.6048,  3.8958,  ...,  0.0608, -1.4891, -0.1590],
        [ 3.1568,  2.0397,  3.4674,  ...,  0.5229,  1.2787,  2.2170],
        [ 3.3461,  3.0029,  1.9368,  ..., -2.0432,  1.0891, -1.3545],
        ...,
        [ 4.7177,  3.4370,  5.1695,  ..., -0.1747,  0.3091,  3.8920],
        [ 3.6575,  5.5972,  2.1359,  ..., -1.4902,  1.9992, -0.1172],
        [-0.3060,  0.5418,  2.7420,  ..., -2.7375,  3.4397,  0.3465]],
       device='cuda:0')}

Round 1
input loaded
{'vision': tensor([[ 0.0265,  0.0322,  0.0012,  ..., -0.0512,  0.0042,  0.0152],
        [-0.0375,  0.0285,  0.0161,  ..., -0.0149,  0.0204,  0.0050],
        [-0.0095,  0.0426,  0.0397,  ...,  0.0225,  0.0070,  0.0031],
        ...,
        [ 0.0288, -0.0065,  0.0568,  ...,  0.0097, -0.0160,  0.0183],
        [ 0.0493,  0.0112,  0.0663,  ...,  0.0092, -0.0194, -0.0061],
        [ 0.0353,  0.0235,  0.0609,  ...,  0.0092, -0.0340,  0.0066]],
       device='cuda:0'), 'text': tensor([[-0.0982,  0.5614, -0.7849,  ..., -0.6212,  0.8541, -1.2849],
        [-3.5873, -1.5544, -3.4510,  ..., -2.0758,  1.7531, -0.1533],
        [-4.6743,  0.3667,  3.1458,  ..., -0.0143, -0.3040,  1.3331],
        ...,
        [ 3.5075,  1.8996,  3.9078,  ..., -3.4550, -3.0547, -0.5101],
        [ 3.5947,  0.9077,  0.5035,  ...,  2.8816, -0.5311,  0.0323],
        [ 1.3310,  0.9197,  1.5350,  ..., -0.7841, -3.1032,  2.5923]],
       device='cuda:0')}

Round 2
input loaded
{'vision': tensor([[-2.2939e-03, -1.4482e-02,  4.7806e-02,  ...,  2.7822e-03,
          7.6808e-03,  3.7713e-03],
        [-1.3423e-02,  2.4289e-02,  3.0461e-02,  ..., -5.0249e-03,
         -9.0290e-03, -2.1367e-02],
        [ 2.6675e-02, -3.4250e-05,  6.1102e-02,  ...,  1.1053e-02,
          4.8536e-03,  4.8595e-03],
        ...,
        [ 9.0327e-03, -3.8984e-03,  4.5772e-02,  ...,  1.5704e-02,
          1.4868e-02, -1.7635e-02],
        [ 4.5862e-02,  3.8634e-02,  4.0603e-02,  ..., -2.2320e-02,
          5.4835e-04, -4.5519e-03],
        [ 3.0373e-02, -2.8048e-03,  4.3141e-02,  ..., -8.2006e-03,
         -1.5075e-02,  8.6035e-03]], device='cuda:0'), 'text': tensor([[ 0.5146, -1.2193,  1.5042,  ..., -0.9723,  2.0385, -2.2427],
        [ 2.5607, -1.8331,  1.6190,  ...,  0.6368, -1.1223,  0.3556],
        [ 1.3181, -0.2769,  3.2979,  ...,  1.0771,  3.0163,  0.4541],
        ...,
        [ 5.6097, -0.6315, -1.0849,  ..., -1.8505,  5.0971,  0.6867],
        [ 1.3782, -1.6242,  2.0492,  ..., -1.5588,  4.7143,  5.9669],
        [-0.5994,  0.4894,  0.1800,  ..., -1.2027, -0.6823,  0.4370]],
       device='cuda:0')}

Round 3
input loaded
{'vision': tensor([[ 0.0451, -0.0056,  0.0219,  ..., -0.0075, -0.0278, -0.0045],
        [ 0.0325,  0.0283,  0.0476,  ...,  0.0047, -0.0243,  0.0228],
        [ 0.0016, -0.0024,  0.0466,  ...,  0.0116, -0.0076, -0.0212],
        ...,
        [ 0.0305, -0.0170,  0.0254,  ..., -0.0277, -0.0036, -0.0009],
        [ 0.0176,  0.0156,  0.0448,  ..., -0.0208,  0.0139, -0.0112],
        [ 0.0061,  0.0194,  0.0685,  ..., -0.0266,  0.0014, -0.0293]],
       device='cuda:0'), 'text': tensor([[ 1.4523, -0.1844,  0.9169,  ..., -3.4328, -3.5795, -0.9804],
        [ 3.0714,  1.3857,  2.8196,  ...,  1.3504,  0.2038,  1.6905],
        [-0.3693,  1.7718,  1.0037,  ...,  2.4896,  3.1376, -3.1425],
        ...,
        [-1.7833, -2.7323,  3.3694,  ...,  0.5663,  2.7323, -0.9995],
        [ 0.1717,  0.3860,  1.9832,  ...,  0.1263,  4.5405, -0.6380],
        [-0.4709,  1.5720,  3.7576,  ..., -1.8097,  3.2098, -0.0098]],
       device='cuda:0')}

Round 4
input loaded
{'vision': tensor([[ 0.0353,  0.0319,  0.0689,  ..., -0.0169, -0.0119, -0.0392],
        [ 0.0346,  0.0048,  0.0404,  ..., -0.0117,  0.0338, -0.0276],
        [ 0.0037, -0.0108,  0.0371,  ..., -0.0068, -0.0143, -0.0024],
        ...,
        [ 0.0269,  0.0006,  0.0405,  ...,  0.0208,  0.0142, -0.0066],
        [ 0.0261,  0.0096,  0.0400,  ..., -0.0035, -0.0096, -0.0271],
        [ 0.0379,  0.0166,  0.0406,  ..., -0.0039, -0.0236, -0.0135]],
       device='cuda:0'), 'text': tensor([[-2.0122, -2.6735,  3.5414,  ..., -1.7174,  4.2610, -0.2349],
        [-0.9019,  0.9551,  3.5432,  ..., -1.9035,  5.6124,  0.2677],
        [-0.8628, -1.5207,  5.3450,  ..., -3.1368,  1.8887, -1.8558],
        ...,
        [-0.5310,  2.4009,  2.1256,  ...,  2.6494,  3.9288,  0.0203],
        [-1.1764,  0.2142,  0.1410,  ...,  1.3653,  5.6151,  1.2758],
        [ 3.2199,  2.9933, -0.0805,  ..., -3.7441, -0.5340, -0.1319]],
       device='cuda:0')}

Round 5
input loaded
{'vision': tensor([[ 0.0153,  0.0052,  0.0397,  ..., -0.0131, -0.0002, -0.0085],
        [ 0.0291,  0.0051,  0.0544,  ..., -0.0039,  0.0014, -0.0138],
        [ 0.0522,  0.0147,  0.0515,  ...,  0.0288, -0.0007,  0.0105],
        ...,
        [ 0.0042,  0.0286,  0.0308,  ..., -0.0221, -0.0037,  0.0130],
        [ 0.0153,  0.0153,  0.0318,  ..., -0.0758, -0.0389, -0.0435],
        [ 0.0054,  0.0205,  0.0292,  ..., -0.0578, -0.0240, -0.0320]],
       device='cuda:0'), 'text': tensor([[-0.3297,  0.3046,  0.9465,  ..., -0.8188,  2.5307, -0.8496],
        [ 2.7848, -2.1517,  3.3539,  ..., -2.7360,  2.8825,  0.5392],
        [ 0.1734,  3.4415,  4.2582,  ...,  1.1452,  4.3254, -0.7163],
        ...,
        [-0.1259,  4.9959, -1.4918,  ...,  0.7156, -0.5504,  2.6598],
        [-2.8466,  3.2279,  0.0789,  ..., -4.6741,  3.1325, -1.6254],
        [-2.2931,  3.6587,  0.1970,  ..., -5.3777,  3.2426, -0.3760]],
       device='cuda:0')}

Round 6
input loaded
{'vision': tensor([[ 0.0107,  0.0037,  0.0377,  ..., -0.0515, -0.0142, -0.0103],
        [-0.0008, -0.0075,  0.0311,  ..., -0.0056,  0.0079, -0.0005],
        [ 0.0256, -0.0230,  0.0580,  ...,  0.0087,  0.0105, -0.0037],
        ...,
        [ 0.0248,  0.0100,  0.0580,  ...,  0.0163,  0.0078,  0.0121],
        [ 0.0128,  0.0101,  0.0610,  ...,  0.0147,  0.0022,  0.0171],
        [ 0.0268, -0.0107,  0.0561,  ..., -0.0081, -0.0087,  0.0050]],
       device='cuda:0'), 'text': tensor([[-2.2463,  3.5266, -0.4262,  ..., -5.7762,  1.0663, -1.0488],
        [ 0.5395,  1.4258, -0.6635,  ...,  0.8443,  2.3273, -1.1728],
        [ 2.5149, -1.0453, -0.0800,  ...,  4.5054,  5.4058, -1.2350],
        ...,
        [ 1.9237,  2.2800,  3.1492,  ...,  1.9382,  1.0062, -1.1336],
        [ 0.3048,  4.0344,  4.3033,  ..., -1.5342,  0.9741,  2.1238],
        [-0.5572, -2.2629,  3.7721,  ..., -2.2380,  1.2093, -1.7739]],
       device='cuda:0')}

Round 7
input loaded
{'vision': tensor([[ 0.0182, -0.0259,  0.0576,  ..., -0.0222, -0.0198,  0.0144],
        [ 0.0069,  0.0046,  0.0397,  ...,  0.0174,  0.0090, -0.0070],
        [ 0.0368,  0.0315,  0.0341,  ..., -0.0188, -0.0079, -0.0041],
        ...,
        [ 0.0356, -0.0144,  0.0643,  ..., -0.0153, -0.0139, -0.0129],
        [ 0.0377,  0.0016,  0.0438,  ..., -0.0134, -0.0208, -0.0153],
        [ 0.0372,  0.0016,  0.0533,  ..., -0.0168, -0.0238,  0.0036]],
       device='cuda:0'), 'text': tensor([[ 3.2408, -2.0993,  3.2589,  ..., -3.7001, -1.3104, -1.9304],
        [ 0.6494,  0.7732,  4.1391,  ...,  0.4106,  6.4874,  0.8577],
        [ 1.5500,  2.7921, -0.9595,  ...,  0.4021,  1.5171,  0.1832],
        ...,
        [ 1.6469, -1.2830,  3.2517,  ..., -6.7200, -0.7321, -1.0745],
        [ 2.0392,  0.8589,  2.2173,  ...,  1.5871, -0.7397, -1.3411],
        [ 1.6890,  1.6027, -0.4497,  ...,  1.1483,  4.5733,  0.5633]],
       device='cuda:0')}

Round 8
input loaded
{'vision': tensor([[ 0.0274,  0.0035,  0.0455,  ..., -0.0149, -0.0205,  0.0127],
        [ 0.0106,  0.0106,  0.0333,  ..., -0.0252, -0.0060,  0.0065],
        [ 0.0184, -0.0111,  0.0335,  ..., -0.0342, -0.0162, -0.0116],
        ...,
        [ 0.0180, -0.0364,  0.0438,  ..., -0.0370, -0.0222, -0.0036],
        [ 0.0394, -0.0313,  0.0466,  ..., -0.0628, -0.0189, -0.0040],
        [ 0.0439, -0.0171,  0.0549,  ..., -0.0624, -0.0412, -0.0042]],
       device='cuda:0'), 'text': tensor([[-0.7549,  3.1594, -1.2322,  ...,  2.7468,  4.8208,  4.4653],
        [-2.8558,  3.8979,  2.8090,  ...,  0.4634,  0.1421,  2.8385],
        [ 0.8164, -3.5171, -0.3813,  ...,  1.8386,  3.9527,  2.4773],
        ...,
        [ 1.4939, -1.9645,  1.8590,  ..., -4.2170, -0.9764, -0.5719],
        [ 1.1368, -0.7610,  0.9480,  ..., -3.9378,  0.4078,  0.3441],
        [ 1.1753, -3.7102,  1.5602,  ..., -2.2714,  3.2394,  1.7576]],
       device='cuda:0')}

Round 9
input loaded
{'vision': tensor([[ 0.0059,  0.0142,  0.0286,  ...,  0.0041,  0.0244,  0.0213],
        [-0.0038, -0.0048,  0.0179,  ..., -0.0024,  0.0126,  0.0259],
        [-0.0191,  0.0195,  0.0290,  ..., -0.0222, -0.0262, -0.0036],
        ...,
        [ 0.0244,  0.0242,  0.0247,  ..., -0.0186, -0.0146,  0.0088],
        [ 0.0393,  0.0093,  0.0626,  ..., -0.0357, -0.0166,  0.0051],
        [ 0.0239,  0.0072,  0.0378,  ..., -0.0113, -0.0170, -0.0144]],
       device='cuda:0'), 'text': tensor([[ 1.7915,  4.0563,  0.1128,  ...,  0.4610,  4.5870,  2.1701],
        [ 2.9333, -0.0742,  4.2272,  ..., -0.3433,  4.4454,  1.4534],
        [ 0.6002,  2.7107, -0.1243,  ...,  0.2878,  1.1151,  0.4997],
        ...,
        [ 2.7380,  6.2975, -1.8231,  ..., -1.6228,  2.9033, -0.8022],
        [ 1.1563,  1.4146,  3.5225,  ..., -2.1772, -1.6614,  1.8817],
        [-1.7514, -0.3427, -0.8618,  ...,  1.2776,  3.8982, -0.0693]],
       device='cuda:0')}

# Ingesting

In [10]:
!pip install lancedb

Collecting lancedb
  Downloading lancedb-0.40.0-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (7.5 kB)
Requirement already satisfied: deprecation>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from lancedb) (2.1.0)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.13/dist-packages (from lancedb) (2.1.3)
Requirement already satisfied: packaging>=23.0 in /usr/local/lib/python3.13/dist-packages (from lancedb) (26.3)
Requirement already satisfied: pyarrow>=16 in /usr/local/lib/python3.13/dist-packages (from lancedb) (23.0.1)
Requirement already satisfied: pydantic<3,>=2.7.4 in /usr/local/lib/python3.13/dist-packages (from lancedb) (2.14.1)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.13/dist-packages (from lancedb) (4.67.3)
Collecting lance-namespace>=0.3.2 (from lancedb)
  Downloading lance_namespace-0.13.0-py3-none-any.whl.metadata (1.6 kB)
Collecting lance-namespace-urllib3-client==0.13.0 (from lance-namespace>=0.3.2->lancedb)
  Downloading lance_namespace_urllib3_client-0.13.0-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from lance-namespace-urllib3-client==0.13.0->lance-namespace>=0.3.2->lancedb) (2.9.0.post0)
Requirement already satisfied: typing-extensions>=4.7.1 in /usr/local/lib/python3.13/dist-packages (from lance-namespace-urllib3-client==0.13.0->lance-namespace>=0.3.2->lancedb) (4.16.0)
Requirement already satisfied: urllib3<3.0.0,>=1.25.3 in /usr/local/lib/python3.13/dist-packages (from lance-namespace-urllib3-client==0.13.0->lance-namespace>=0.3.2->lancedb) (2.5.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2.7.4->lancedb) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2.7.4->lancedb) (2.50.1)
Requirement already satisfied: typing-inspection>=0.4.4 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2.7.4->lancedb) (0.4.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->lance-namespace-urllib3-client==0.13.0->lance-namespace>=0.3.2->lancedb) (1.17.0)
Downloading lancedb-0.40.0-cp310-abi3-manylinux_2_28_x86_64.whl (75.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.2/75.2 MB 28.7 MB/s eta 0:00:00
Downloading lance_namespace-0.13.0-py3-none-any.whl (13 kB)
Downloading lance_namespace_urllib3_client-0.13.0-py3-none-any.whl (406 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 406.8/406.8 kB 41.1 MB/s eta 0:00:00
Installing collected packages: lance-namespace-urllib3-client, lance-namespace, lancedb
Successfully installed lance-namespace-0.13.0 lance-namespace-urllib3-client-0.13.0 lancedb-0.40.0

In [11]:
all_embeddings[0]['vision'].shape

torch.Size([100, 1024])

In [12]:
all_embeddings[0]['vision'][0:2].shape

torch.Size([2, 1024])

In [ ]:
#image_df

shape: (500, 6)
┌─────────┬──────────────┬────────────────────┬────────────────────┬───────────────────┬───────────┐
│ dex_num ┆ name         ┆ page_title         ┆ image_path         ┆ text              ┆ use_image │
│ ---     ┆ ---          ┆ ---                ┆ ---                ┆ ---               ┆ ---       │
│ str     ┆ str          ┆ str                ┆ str                ┆ str               ┆ bool      │
╞═════════╪══════════════╪════════════════════╪════════════════════╪═══════════════════╪═══════════╡
│ 0004    ┆ Charmander   ┆ Charmander         ┆ data/pokemon_data/ ┆ Charmander is a   ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/0004_…      ┆ bipedal, repti…   ┆           │
│ 0006    ┆ Charizard    ┆ Charizard          ┆ data/pokemon_data/ ┆ Charizard is a    ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/0006_…      ┆ draconic , bipe…  ┆           │
│ 0012    ┆ Butterfree   ┆ Butterfree         ┆ data/pokemon_data/ ┆ Butterfree is a   ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/0012_…      ┆ lepidopteran i…   ┆           │
│ 0013    ┆ Weedle       ┆ Weedle (Pokémon)   ┆ data/pokemon_data/ ┆ Weedle is a       ┆ true      │
│         ┆              ┆                    ┆ images/0013_…      ┆ larval insect     ┆           │
│         ┆              ┆                    ┆                    ┆ Poké…             ┆           │
│ 0014    ┆ Kakuna       ┆ Kakuna (Pokémon)   ┆ data/pokemon_data/ ┆ Kakuna is a       ┆ true      │
│         ┆              ┆                    ┆ images/0014_…      ┆ yellow, insect    ┆           │
│         ┆              ┆                    ┆                    ┆ coc…              ┆           │
│ …       ┆ …            ┆ …                  ┆ …                  ┆ …                 ┆ …         │
│ 1010    ┆ Iron Leaves  ┆ Iron Leaves        ┆ data/pokemon_data/ ┆ Iron Leaves is a  ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/1010_…      ┆ mechanical Po…    ┆           │
│ 1012    ┆ Poltchageist ┆ Poltchageist       ┆ data/pokemon_data/ ┆ Poltchageist is a ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/1012_…      ┆ Pokémon made…     ┆           │
│ 1013    ┆ Sinistcha    ┆ Sinistcha          ┆ data/pokemon_data/ ┆ Sinistcha is a    ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/1013_…      ┆ Pokémon made of…  ┆           │
│ 1018    ┆ Archaludon   ┆ Archaludon         ┆ data/pokemon_data/ ┆ Archaludon is a   ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/1018_…      ┆ tall, metallic…   ┆           │
│ 1021    ┆ Raging Bolt  ┆ Raging Bolt        ┆ data/pokemon_data/ ┆ Raging Bolt is a  ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/1021_…      ┆ massive quadr…    ┆           │
└─────────┴──────────────┴────────────────────┴────────────────────┴───────────────────┴───────────┘

In [ ]:
#text_df

shape: (500, 6)
┌─────────┬──────────────┬────────────────────┬────────────────────┬───────────────────┬───────────┐
│ dex_num ┆ name         ┆ page_title         ┆ image_path         ┆ text              ┆ use_image │
│ ---     ┆ ---          ┆ ---                ┆ ---                ┆ ---               ┆ ---       │
│ str     ┆ str          ┆ str                ┆ str                ┆ str               ┆ bool      │
╞═════════╪══════════════╪════════════════════╪════════════════════╪═══════════════════╪═══════════╡
│ 0001    ┆ Bulbasaur    ┆ Bulbasaur          ┆ data/pokemon_data/ ┆ Bulbasaur is a    ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/0001_…      ┆ small, quadrupe…  ┆           │
│ 0002    ┆ Ivysaur      ┆ Ivysaur (Pokémon)  ┆ data/pokemon_data/ ┆ Ivysaur is a      ┆ false     │
│         ┆              ┆                    ┆ images/0002_…      ┆ quadrupedal       ┆           │
│         ┆              ┆                    ┆                    ┆ amphi…            ┆           │
│ 0003    ┆ Venusaur     ┆ Venusaur (Pokémon) ┆ data/pokemon_data/ ┆ Venusaur is a     ┆ false     │
│         ┆              ┆                    ┆ images/0003_…      ┆ squat, quadruped… ┆           │
│ 0005    ┆ Charmeleon   ┆ Charmeleon         ┆ data/pokemon_data/ ┆ Charmeleon is a   ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/0005_…      ┆ bipedal, repti…   ┆           │
│ 0007    ┆ Squirtle     ┆ Squirtle (Pokémon) ┆ data/pokemon_data/ ┆ Squirtle is a     ┆ false     │
│         ┆              ┆                    ┆ images/0007_…      ┆ small reptilian … ┆           │
│ …       ┆ …            ┆ …                  ┆ …                  ┆ …                 ┆ …         │
│ 1019    ┆ Hydrapple    ┆ Hydrapple          ┆ data/pokemon_data/ ┆ Hydrapple is a    ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/1019_…      ┆ Pokémon compose…  ┆           │
│ 1020    ┆ Gouging Fire ┆ Gouging Fire       ┆ data/pokemon_data/ ┆ Gouging Fire is a ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/1020_…      ┆ massive lion…     ┆           │
│ 1022    ┆ Iron Boulder ┆ Iron Boulder       ┆ data/pokemon_data/ ┆ Iron Boulder is a ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/1022_…      ┆ spherical, b…     ┆           │
│ 1023    ┆ Iron Crown   ┆ Iron Crown         ┆ data/pokemon_data/ ┆ Iron Crown is an  ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/1023_…      ┆ armored turqu…    ┆           │
│ 1025    ┆ Pecharunt    ┆ Pecharunt          ┆ data/pokemon_data/ ┆ Pecharunt is a    ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/1025_…      ┆ small Pokémon r…  ┆           │
└─────────┴──────────────┴────────────────────┴────────────────────┴───────────────────┴───────────┘

In [ ]:
to_ingest = []

round = 0
for i in range(0, len(images), batch_size):
    print("Round", round)

    # vision and text set set
    data_part = full_df.slice(i, i+batch_size).to_dict(as_series=False)
    vals = list(data_part.values()) + [all_embeddings[round]['vision'].tolist(), all_embeddings[round]['text'].tolist()]
    keys = list(data_part.keys()) + ["image_vector", "text_vector"]

    data_ingest = [dict(zip(keys, values)) for values in zip(*vals)]

    to_ingest += data_ingest
    round += 1

print(len(to_ingest))
to_ingest[0]

Round 0
Round 1
Round 2
Round 3
Round 4
Round 5
Round 6
Round 7
Round 8
Round 9
1000

{'dex_num': '0001',
 'name': 'Bulbasaur',
 'page_title': 'Bulbasaur (Pokémon)',
 'image_path': 'data/pokemon_data/images/0001_Bulbasaur.png',
 'text': "Bulbasaur is a small, quadrupedal amphibian Pokémon that has blue-green skin with darker patches. It has red eyes with white pupils, pointed, ear-like structures on top of its head, and a short, blunt snout with a wide mouth. Small, pointed teeth are visible in the upper jaw when the mouth is open. Each of its thick legs ends with three sharp claws. On Bulbasaur's back is a green plant bulb that conceals two slender, tentacle-like vines, which grow from a seed planted there at birth. The bulb also provides it with energy through photosynthesis and from the nutrient-rich seeds contained within.",
 'image_vector': [0.009552144445478916,
  0.0426461435854435,
  0.03044852800667286,
  -0.015861453488469124,
  0.025874421000480652,
  0.019172558560967445,
  -0.036615606397390366,
  -0.006718929391354322,
  -0.009552144445478916,
  0.056027110666036606,
  0.0008220874588005245,
  -0.025259988382458687,
  -0.012072454206645489,
  0.006963564548641443,
  0.0015830162446945906,
  -0.029902365058660507,
  -0.011844886466860771,
  -0.004983727820217609,
  -0.035341229289770126,
  0.0011421042727306485,
  0.05156678706407547,
  0.06321824342012405,
  -0.06153424456715584,
  -0.017078937962651253,
  -0.013460615649819374,
  -0.02149374783039093,
  -0.007168375421315432,
  0.03802652284502983,
  -0.008698766119778156,
  -0.03859544172883034,
  0.011958670802414417,
  -0.016248317435383797,
  0.040871117264032364,
  -0.027217069640755653,
  0.04539971053600311,
  0.026784691959619522,
  -0.019695963710546494,
  0.009415604174137115,
  -0.02805906906723976,
  0.01787542551755905,
  -0.023871827870607376,
  0.0026966745499521494,
  0.013403723947703838,
  -0.016248317435383797,
  -0.08738590776920319,
  -0.010502238757908344,
  -0.027285339310765266,
  -0.06735996901988983,
  0.014894290827214718,
  0.014245723374187946,
  -0.007367496844381094,
  -0.003589876927435398,
  0.031700149178504944,
  -0.00694649713113904,
  -0.006622213404625654,
  -0.03593290224671364,
  -0.009552144445478916,
  -0.024986907839775085,
  -0.016180047765374184,
  0.012982724234461784,
  -0.028491446748375893,
  -0.027262583374977112,
  0.04175863042473793,
  0.02197163924574852,
  0.012709642760455608,
  -0.000254946673521772,
  0.0384133905172348,
  0.016191424801945686,
  -0.03497711941599846,
  0.01085496786981821,
  -0.01421158853918314,
  -0.001402384485118091,
  0.02960652858018875,
  0.037525877356529236,
  -0.061352189630270004,
  0.048016734421253204,
  0.013096507638692856,
  -0.007475591264665127,
  -0.018580883741378784,
  -0.0005689186509698629,
  -0.0067701321095228195,
  0.0005123823648318648,
  -0.03297452628612518,
  0.008448442444205284,
  0.011958670802414417,
  -0.002271407749503851,
  0.042099982500076294,
  -0.022005774080753326,
  0.010502238757908344,
  0.006992010399699211,
  0.02437247522175312,
  -0.013984020799398422,
  -0.04612792655825615,
  -0.01669207401573658,
  -0.02389458380639553,
  -0.003993809223175049,
  -0.05197640880942345,
  -0.015576993115246296,
  -0.0017480025999248028,
  0.00805588811635971,
  0.028354907408356667,
  -0.0357280932366848,
  -0.035113658756017685,
  0.010098306462168694,
  0.037616901099681854,
  0.05256808549165726,
  0.010451036505401134,
  0.00593382166698575,
  0.010832211934030056,
  0.014700858853757381,
  -0.035819120705127716,
  0.006684794556349516,
  0.05670981481671333,
  0.014575696550309658,
  0.030653338879346848,
  -0.014814642257988453,
  -0.0024691070429980755,
  0.033361390233039856,
  0.023484962061047554,
  -0.014518804848194122,
  0.044079817831516266,
  -0.027171555906534195,
  -0.01220899447798729,
  -0.023803558200597763,
  0.029083123430609703,
  0.01554285828024149,
  0.039005063474178314,
  0.053887978196144104,
  -0.00242643803358078,
  -0.006764443125575781,
  -0.02596544846892357,
  0.022733990103006363,
  0.030357500538229942,
  0.014678101986646652,
  -0.01913842372596264,
  0.02607923187315464,
  -0.0037434848491102457,
  0.03525020182132721,
  0.009620415046811104,
  -0.013745075091719627,
  -0.028172852471470833,
  0.027603933587670326,
  -0.04166760295629501,
  0.02635231241583824,
  -0.04030219838023186,
  0.0036809039302170277,
  -0.006952186115086079,
  0.008789793588221073,
  -0.012459319084882736,
  0.007384564261883497,
  0.03993809223175049,
  -0.014450534246861935,
  0.006593767553567886,
  -0.004298180807381868,
  -0.013949885964393616,
  0.029788581654429436,
  -0.012322778813540936,
  -0.03593290224671364,
  0.012334156781435013,
  0.023735286667943,
  -0.014439156278967857,
  -0.00013582933752331883,
  -0.012868940830230713,
  0.0054502408020198345,
  0.007708847988396883,
  -0.009005982428789139,
  0.0021277558989822865,
  -0.024827610701322556,
  0.05288667976856232,
  -0.02644333988428116,
  -0.031495336443185806,
  -0.011588873341679573,
  0.02719431184232235,
  0.02837766334414482,
  -0.014678101986646652,
  -0.017773019149899483,
  0.03543225675821304,
  0.009637482464313507,
  -0.015099101699888706,
  -0.01357439998537302,
  0.0031688769813627005,
  -0.014700858853757381,
  0.01904739812016487,
  0.020276261493563652,
  -0.0194570180028677,
  -0.015918344259262085,
  0.0199918020516634,
  -0.019604938104748726,
  -0.022176450118422508,
  -0.013346832245588303,
  0.02976582571864128,
  0.058484841138124466,
  0.01877431571483612,
  -0.000985651626251638,
  0.004238443914800882,
  0.0035984106361865997,
  -0.00776005070656538,
  9.902740566758439e-05,
  0.0178640466183424,
  -0.01128165703266859,
  0.028400421142578125,
  -0.024827610701322556,
  -0.026420583948493004,
  0.018592262640595436,
  -0.028969338163733482,
  0.0030380256939679384,
  0.012447940185666084,
  -0.007088726852089167,
  0.039960846304893494,
  -0.027490150183439255,
  -0.019422883167862892,
  0.024713827297091484,
  0.02805906906723976,
  0.009540766477584839,
  0.005626605823636055,
  0.0002992156660184264,
  0.01851261407136917,
  0.00933595560491085,
  0.026534367352724075,
  0.006792888976633549,
  -0.031336039304733276,
  0.05739251524209976,
  0.011844886466860771,
  -0.013972642831504345,
  0.036661118268966675,
  0.004727714229375124,
  -0.03286074101924896,
  -0.03449922800064087,
  0.03859544172883034,
  -0.032610420137643814,
  -0.027012258768081665,
  0.023166367784142494,
  0.012971345335245132,
  -0.004204309079796076,
  -0.029743067920207977,
  0.006343443412333727,
  0.02239263989031315,
  0.012322778813540936,
  -0.04175863042473793,
  -0.017374776303768158,
  0.004744781646877527,
  0.023530475795269012,
  -0.02853696048259735,
  -0.030471283942461014,
  -0.05985024571418762,
  0.0010859235189855099,
  -0.011196319945156574,
  0.044125333428382874,
  0.0011549049522727728,
  0.019900774583220482,
  0.10577335953712463,
  0.011844886466860771,
  0.0023069651797413826,
  0.03456749767065048,
  -0.015918344259262085,
  -0.0025387995410710573,
  0.02239263989031315,
  -0.01946839690208435,
  -0.029196906834840775,
  -0.008545158430933952,
  0.011833508498966694,
  -0.007492659147828817,
  -0.01288031879812479,
  0.0023425226099789143,
  -0.004830119665712118,
  0.010047104209661484,
  -0.027558419853448868,
  -0.004611085634678602,
  -0.052021924406290054,
  0.01236829161643982,
  0.009950387291610241,
  -0.005205605644732714,
  -0.01776164025068283,
  0.0031688769813627005,
  0.002336833393201232,
  -0.05183986946940422,
  0.007321983575820923,
  0.020287640392780304,
  -0.00997314415872097,
  -0.008710145018994808,
  0.02197163924574852,
  -0.020515207201242447,
  -0.005649362225085497,
  0.005893997382372618,
  -0.01866053231060505,
  -0.05734700337052345,
  0.016248317435383797,
  0.050793059170246124,
  0.02432696335017681,
  -0.010894793085753918,
  0.08192428946495056,
  0.00304655940271914,
  -0.027262583374977112,
  0.06726894527673721,
  0.007304915692657232,
  0.0038231334183365107,
  0.047925710678100586,
  0.013847480528056622,
  -0.027717716991901398,
  -0.02937895990908146,
  0.004158795345574617,
  0.006548253819346428,
  0.01977561227977276,
  -0.024941394105553627,
  0.03140431270003319,
  -0.01835331693291664,
  0.014268480241298676,
  0.025100691244006157,
  0.03902782127261162,
  -0.004010876640677452,
  -0.012174859642982483,
  -0.011810751631855965,
  -0.0199918020516634,
  -0.04410257562994957,
  0.04742506146430969,
  0.0019371680682525039,
  0.02309809811413288,
  0.0072650914080441,
  0.04883597791194916,
  0.03365723043680191,
  0.021664423868060112,
  -0.038208577781915665,
  -0.04093938693404198,
  -0.052613597363233566,
  -0.03279247134923935,
  -0.04043873772025108,
  0.00922786071896553,
  -0.008471199311316013,
  0.005069065373390913,
  -0.02260882779955864,
  -0.0018560971366241574,
  -0.03263317421078682,
  0.013585777953267097,
  0.032451122999191284,
  0.0035443634260445833,
  0.029743067920207977,
  0.013995399698615074,
  -0.024122152477502823,
  -0.017465803772211075,
  0.006627902388572693,
  0.016441749408841133,
  -0.012777913361787796,
  0.025988204404711723,
  -0.03556879609823227,
  -0.0034789377823472023,
  0.003618322778493166,
  -0.022483665496110916,
  -0.05306873470544815,
  0.015702156350016594,
  0.06590353697538376,
  0.023553233593702316,
  -0.010012968443334103,
  0.01434812881052494,
  -0.03327036276459694,
  0.009449739009141922,
  0.011799373663961887,
  -0.00629224069416523,
  -0.01434812881052494,
  0.03449922800064087,
  0.010377076454460621,
  -0.02032177522778511,
  0.018159884959459305,
  -0.018626397475600243,
  -0.005151558667421341,
  -0.008203807286918163,
  -0.027535663917660713,
  -0.032564904540777206,
  0.028468690812587738,
  0.011970048770308495,
  -0.03743484988808632,
  -0.01482602022588253,
  -0.013824723660945892,
  0.010786698199808598,
  -0.03131328523159027,
  0.005967956967651844,
  0.04339711740612984,
  -0.008328969590365887,
  -0.007799874991178513,
  0.024600043892860413,
  -0.013665426522493362,
  -0.003979586064815521,
  0.11105292290449142,
  -0.03866371139883995,
  -0.0020353065337985754,
  -0.022381260991096497,
  0.05748354271054268,
  -0.008124158717691898,
  -0.011810751631855965,
  0.003734951140359044,
  -0.0038771808613091707,
  0.02127755805850029,
  0.045900359749794006,
  0.01988939754664898,
  0.010354319587349892,
  0.05752905458211899,
  0.025897178798913956,
  -0.03802652284502983,
  -0.023439450189471245,
  0.027535663917660713,
  0.008010375313460827,
  0.020492451265454292,
  0.0064287809655070305,
  -0.015918344259262085,
  -0.011361305601894855,
  -0.015611128881573677,
  0.03647906705737114,
  -0.004619619809091091,
  0.0041275047697126865,
  -0.01663518138229847,
  -0.008732901886105537,
  -0.000847688817884773,
  0.019343234598636627,
  0.006781510543078184,
  -0.0357280932366848,
  0.03142706677317619,
  -0.023871827870607376,
  0.022893287241458893,
  -0.023280153051018715,
  0.005566869396716356,
  0.009910563006997108,
  -0.04405706375837326,
  -0.007481280714273453,
  -0.014154696837067604,
  0.01018933393061161,
  -0.03834511712193489,
  0.024713827297091484,
  -0.009472495876252651,
  -0.002149090403690934,
  0.006320686545222998,
  -0.011628697626292706,
  0.018273668363690376,
  0.053569383919239044,
  0.02842317707836628,
  0.008016063831746578,
  -0.05639122053980827,
  0.0021135329734534025,
  -0.008949090726673603,
  -0.0319959856569767,
  0.0036809039302170277,
  -0.011088225059211254,
  -0.01904739812016487,
  -0.009375779889523983,
  -0.018944991752505302,
  0.0030693162698298693,
  -0.030198203399777412,
  -0.0015759047819301486,
  -0.026534367352724075,
  0.04084835946559906,
  -0.004016565624624491,
  0.0009202259825542569,
  -0.04526317119598389,
  0.02607923187315464,
  -0.002089353743940592,
  0.04196344316005707,
  0.05739251524209976,
  -0.034430958330631256,
  -0.022472288459539413,
  0.37794405221939087,
  -0.015474587678909302,
  0.04112144187092781,
  -0.012015562504529953,
  -0.005848484113812447,
  0.013073750771582127,
  -0.020867936313152313,
  0.018922235816717148,
  -0.027057772502303123,
  0.03604668751358986,
  -0.0248048547655344,
  -0.009375779889523983,
  -0.0013213136699050665,
  0.05193089693784714,
  0.006792888976633549,
  -0.0006617235485464334,
  0.004008031915873289,
  -0.02953825704753399,
  -0.07546137273311615,
  0.01554285828024149,
  -0.03591014817357063,
  0.006701861973851919,
  -0.0017565364250913262,
  -0.010655846446752548,
  -0.011981427669525146,
  0.028400421142578125,
  0.024008367210626602,
  0.03001614846289158,
  0.025715123862028122,
  0.013244426809251308,
  0.010672914795577526,
  0.09089044481515884,
  -0.021152395755052567,
  0.005808659829199314,
  0.03652457892894745,
  -0.017579587176442146,
  -0.015155993402004242,
  -0.000944404979236424,
  -0.03422614932060242,
  0.015599749982357025,
  0.04915457218885422,
  0.01371094025671482,
  -0.061625272035598755,
  0.03258766233921051,
  -0.01994628831744194,
  -0.012629994191229343,
  -0.021983018144965172,
  0.04216825217008591,
  0.020264882594347,
  -0.03267868980765343,
  -0.008715834468603134,
  0.01306237280368805,
  0.03984706476330757,
  -0.06572148203849792,
  -0.028878312557935715,
  -0.10103995352983475,
  -0.0042612007819116116,
  -0.024554530158638954,
  0.036820415407419205,
  0.02330290898680687,
  0.0210727471858263,
  -0.022210584953427315,
  -0.01722685806453228,
  0.004670822527259588,
  -0.019798370078206062,
  -0.03370274230837822,
  -0.016202803701162338,
  -0.008971847593784332,
  0.028764527291059494,
  -0.006462916266173124,
  -0.016077641397714615,
  0.006952186115086079,
  -0.014120561070740223,
  0.014234345406293869,
  -0.03370274230837822,
  -0.032929014414548874,
  -0.012732399627566338,
  -0.003228613408282399,
  -0.019127046689391136,
  0.07400494068861008,
  -0.0037747754249721766,
  -0.002099309815093875,
  0.030334744602441788,
  0.0031745661981403828,
  -0.009028739295899868,
  -0.1279839426279068,
  0.05243154615163803,
  -0.04148554801940918,
  -0.004517214372754097,
  0.020230747759342194,
  -0.007572307717055082,
  -0.021300315856933594,
  0.01909290999174118,
  0.003362309420481324,
  -0.017590966075658798,
  0.023371178656816483,
  0.0025003976188600063,
  -0.009182346984744072,
  -0.012061076238751411,
  -0.02000318095088005,
  -0.03716176748275757,
  -0.007572307717055082,
  -0.025464799255132675,
  -0.03857268765568733,
  -0.019752856343984604,
  -0.019536666572093964,
  0.03907333314418793,
  -0.06735996901988983,
  0.02405388094484806,
  -0.030630581080913544,
  0.006935118697583675,
  -0.05552646145224571,
  -0.022062666714191437,
  -0.0063491323962807655,
  0.00027272538864053786,
  0.033361390233039856,
  -0.03743484988808632,
  0.0194570180028677,
  0.01716996543109417,
  -0.01621418260037899,
  -0.005296632647514343,
  0.007555239833891392,
  0.018580883741378784,
  -0.021152395755052567,
  0.002560134045779705,
  -0.022221963852643967,
  0.10431692749261856,
  -0.04216825217008591,
  -0.005077599082142115,
  0.029629284515976906,
  -0.01621418260037899,
  -0.030334744602441788,
  -0.02000318095088005,
  -0.04751608893275261,
  0.032291822135448456,
  -0.00791934784501791,
  -0.05798419192433357,
  0.006121565122157335,
  -0.007083037402480841,
  0.03279247134923935,
  0.003945451229810715,
  0.014769128523766994,
  0.009739887900650501,
  -0.018637776374816895,
  0.015144615434110165,
  0.019400127232074738,
  -0.040825605392456055,
  0.003291194560006261,
  -0.0157362911850214,
  0.00685547012835741,
  0.01962769404053688,
  0.0026212928351014853,
  0.004067768342792988,
  -0.00226002954877913,
  -0.061352189630270004,
  -0.018762938678264618,
  0.021448234096169472,
  0.015076344832777977,
  -0.02405388094484806,
  0.01069567073136568,
  -0.004778916947543621,
  -0.004409119952470064,
  0.016657939180731773,
  -0.013813345693051815,
  0.007765739690512419,
  0.029105879366397858,
  -0.01538356114178896,
  -0.04879046604037285,
  0.031700149178504944,
  0.02644333988428116,
  -0.022631585597991943,
  0.038003768771886826,
  0.04560451954603195,
  0.036342523992061615,
  -0.005535578820854425,
  -0.01599799282848835,
  -0.009370090439915657,
  -0.024190422147512436,
  -0.02207404375076294,
  -0.10058481991291046,
  0.0075381724163889885,
  0.0074585238471627235,
  0.03270144388079643,
  0.010957373306155205,
  -0.007202510256320238,
  0.033679984509944916,
  0.016976533457636833,
  0.022324368357658386,
  -0.04810776188969612,
  0.07291261851787567,
  -0.0634913221001625,
  -0.014291237108409405,
  0.0009621836943551898,
  -0.028081825003027916,
  -0.028013555333018303,
  0.027535663917660713,
  -0.026101989671587944,
  -0.022096801549196243,
  -0.0021106882486492395,
  0.01484877709299326,
  0.017522694543004036,
  -0.012516210786998272,
  0.014257102273404598,
  0.06157975643873215,
  0.020287640392780304,
  -0.017090316861867905,
  0.023871827870607376,
  -0.0218692347407341,
  0.030220959335565567,
  0.031062958762049675,
  0.004448944237083197,
  -0.020196612924337387,
  0.0033224851358681917,
  0.0035329849924892187,
  0.0022216273937374353,
  -0.03381652757525444,
  0.010519306175410748,
  0.0263978261500597,
  0.06594905257225037,
  0.020253505557775497,
  0.008920644409954548,
  -0.015815939754247665,
  0.01952528953552246,
  -0.025737881660461426,
  0.0357280932366848,
  0.028150096535682678,
  0.041189711540937424,
  0.041349008679389954,
  -0.0024918639101088047,
  -0.003208701265975833,
  -0.003524451283738017,
  -0.02288190834224224,
  -0.015110479667782784,
  -0.007686091121286154,
  -0.024782096967101097,
  0.011310103349387646,
  0.03452198579907417,
  -0.0005582514568232,
  0.003715038998052478,
  0.046059656888246536,
  0.014120561070740223,
  0.013608534820377827,
  0.025100691244006157,
  0.013392345979809761,
  0.00885806418955326,
  -0.017829911783337593,
  -0.03204150125384331,
  0.014780507422983646,
  0.021357206627726555,
  0.01961631514132023,
  -0.02500966563820839,
  0.011054090224206448,
  -0.01897912658751011,
  0.0346812829375267,
  -0.0210727471858263,
  -0.01728374883532524,
  0.01802334375679493,
  0.027262583374977112,
  0.012163481675088406,
  -0.007435766980051994,
  0.005771679803729057,
  0.0003132608544547111,
  0.0010055637685582042,
  -0.0021064213942736387,
  -0.017693370580673218,
  -0.04323782026767731,
  0.031062958762049675,
  -0.00914252270013094,
  0.027922527864575386,
  -0.028719015419483185,
  -0.012800670228898525,
  0.005327923223376274,
  0.038686469197273254,
  0.006735997274518013,
  0.023758044466376305,
  0.013506129384040833,
  0.028605230152606964,
  0.003968207631260157,
  -0.029151393100619316,
  -0.03176841884851456,
  0.023109477013349533,
  0.02981133945286274,
  -0.013153399340808392,
  0.038481660187244415,
  -0.0014934114878997207,
  -0.03104020282626152,
  -0.02660263702273369,
  0.008260698989033699,
  0.02425869181752205,
  -0.011133738793432713,
  0.04842635616660118,
  -0.02078828774392605,
  -0.02111826092004776,
  -0.02298431470990181,
  -0.007401632145047188,
  -0.0035272957757115364,
  -0.04874495044350624,
  -0.018057478591799736,
  -0.33516135811805725,
  0.024827610701322556,
  -0.01319891307502985,
  0.005985024385154247,
  -3.8863145164214075e-06,
  -0.024873124435544014,
  0.041735872626304626,
  -0.0009749843738973141,
  0.041144199669361115,
  -0.007219578139483929,
  -0.011765237897634506,
  -0.038800254464149475,
  0.004173018503934145,
  0.007828321307897568,
  0.002511776052415371,
  0.047334033995866776,
  -0.008937712758779526,
  -0.010633089579641819,
  -0.006616524420678616,
  -0.03470404073596001,
  0.0016768877394497395,
  0.037047985941171646,
  -0.01290307566523552,
  0.0035756537690758705,
  0.00890926644206047,
  -0.01797783002257347,
  -0.006815645843744278,
  0.0018660532077774405,
  -0.027877015992999077,
  0.028764527291059494,
  -0.016555532813072205,
  0.00043806739267893136,
  0.02805906906723976,
  0.01579318195581436,
  -0.015986613929271698,
  0.07755499333143234,
  -0.0031006068456918,
  0.0066392808221280575,

In [1]:
import lancedb

uri = "pokemon_db"
db = lancedb.connect(uri)

In [15]:
table = db.create_table("pokemon", data=to_ingest, mode="overwrite")

In [16]:
len(all_embeddings[0]['text'][0].tolist())

1024

In [20]:
query_vector = all_embeddings[0]['text'][0].tolist()
#query_vector = all_embeddings[2]['text'][95].tolist()

result = (
    table.search(query_vector, vector_column_name="text_vector")
    .select(["name", "_distance"])
    .limit(10)
    .to_polars()
)
print(result)

shape: (10, 2)
┌────────────┬─────────────┐
│ name       ┆ _distance   │
│ ---        ┆ ---         │
│ str        ┆ f32         │
╞════════════╪═════════════╡
│ Bulbasaur  ┆ 0.0         │
│ Venusaur   ┆ 4113.521973 │
│ Ivysaur    ┆ 4364.966309 │
│ Charmander ┆ 5354.098145 │
│ Squirtle   ┆ 5372.14209  │
│ Leafeon    ┆ 5392.914062 │
│ Glaceon    ┆ 6174.446289 │
│ Snorlax    ┆ 6400.994629 │
│ Charizard  ┆ 6464.520996 │
│ Shroomish  ┆ 6626.084961 │
└────────────┴─────────────┘

In [21]:
!zip -r pokemon_db.zip pokemon_db

  adding: pokemon_db/ (stored 0%)
  adding: pokemon_db/pokemon.lance/ (stored 0%)
  adding: pokemon_db/pokemon.lance/data/ (stored 0%)
  adding: pokemon_db/pokemon.lance/data/101101100110010111000011189889473ba2f016ff4865e45f.lance (deflated 15%)
  adding: pokemon_db/pokemon.lance/_transactions/ (stored 0%)
  adding: pokemon_db/pokemon.lance/_transactions/0-7a153862-bc47-4926-b44d-c20cfd16481a.txn (deflated 43%)
  adding: pokemon_db/pokemon.lance/_versions/ (stored 0%)
  adding: pokemon_db/pokemon.lance/_versions/latest_version_hint.json (stored 0%)
  adding: pokemon_db/pokemon.lance/_versions/18446744073709551614.manifest (deflated 63%)

In [2]:
db.list_tables()

ListTablesResponse(context=None, tables=[], page_token=None)

In [ ]:
#db.drop_table("pokemon")