In [2]:
!pip install git+https://github.com/facebookresearch/ImageBind.git#egg=imagebind
!pip install setuptools<82
!pip install torchcodec

Collecting imagebind
  Cloning https://github.com/facebookresearch/ImageBind.git to /tmp/pip-install-k9bkqnz0/imagebind_b6703072cb9a4ac68dd3e7b84bd38712
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/ImageBind.git /tmp/pip-install-k9bkqnz0/imagebind_b6703072cb9a4ac68dd3e7b84bd38712
  Resolved https://github.com/facebookresearch/ImageBind.git to commit 53680b02d7e37b19b124fa37bae4b6c98c38f5be
  Preparing metadata (setup.py) ... done
Collecting pytorchvideo@ git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f (from imagebind)
  Cloning https://github.com/facebookresearch/pytorchvideo.git (to revision 6cdc929315aab1b5674b6dcf73b16ec99147735f) to /tmp/pip-install-k9bkqnz0/pytorchvideo_ba992acd0c2b4f33831fe1879d5e59eb
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/pytorchvideo.git /tmp/pip-install-k9bkqnz0/pytorchvideo_ba992acd0c2b4f33831fe1879d5e59eb
  Running command git rev-parse -q --verify 'sha^6cdc929315aab1b5674b6dcf73b16ec99147735f'
  Running command git fetch -q https://github.com/facebookresearch/pytorchvideo.git 6cdc929315aab1b5674b6dcf73b16ec99147735f
  Running command git checkout -q 6cdc929315aab1b5674b6dcf73b16ec99147735f
  Resolved https://github.com/facebookresearch/pytorchvideo.git to commit 6cdc929315aab1b5674b6dcf73b16ec99147735f
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from imagebind) (2.11.0+cu130)
Requirement already satisfied: torchvision in /usr/local/lib/python3.13/dist-packages (from imagebind) (0.26.0+cu130)
Requirement already satisfied: torchaudio in /usr/local/lib/python3.13/dist-packages (from imagebind) (2.11.0+cu130)
Requirement already satisfied: timm in /usr/local/lib/python3.13/dist-packages (from imagebind) (1.0.30)
Collecting ftfy (from imagebind)
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.13/dist-packages (from imagebind) (2025.11.3)
Requirement already satisfied: einops in /usr/local/lib/python3.13/dist-packages (from imagebind) (0.8.2)
Collecting iopath (from imagebind)
  Downloading iopath-0.1.10.tar.gz (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.19 in /usr/local/lib/python3.13/dist-packages (from imagebind) (2.1.3)
Collecting types-regex (from imagebind)
  Downloading types_regex-2026.9.29.20261005-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (4.0.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (2025.12.0)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (13.0.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->imagebind) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->imagebind) (13.0.85)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.13/dist-packages (from ftfy->imagebind) (0.9.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from iopath->imagebind) (4.67.3)
Collecting portalocker (from iopath->imagebind)
  Downloading portalocker-4.4.0-py3-none-any.whl.metadata (10 kB)
Collecting fvcore (from pytorchvideo@ git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f->imagebind)
  Downloading fvcore-0.1.5.post20221221.tar.gz (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 7.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting av (from pytorchvideo@ git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f->imagebind)
  Downloading av-19.0.1-cp312-abi3-manylinux_2_28_x86_64.whl.metadata (5.0 kB)
Collecting parameterized (from pytorchvideo@ git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f->imagebind)
  Downloading parameterized-0.9.0-py2.py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from timm->imagebind) (6.0.3)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.13/dist-packages (from timm->imagebind) (1.33.0)
Requirement already satisfied: safetensors in /usr/local/lib/python3.13/dist-packages (from timm->imagebind) (0.8.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.13/dist-packages (from torchvision->imagebind) (11.3.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch>=2.0.0->imagebind) (1.8.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.0.0->imagebind) (1.3.0)
Collecting yacs>=0.1.6 (from fvcore->pytorchvideo@ git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f->imagebind)
  Downloading yacs-0.1.8-py3-none-any.whl.metadata (639 bytes)
Requirement already satisfied: termcolor>=1.1 in /usr/local/lib/python3.13/dist-packages (from fvcore->pytorchvideo@ git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f->imagebind) (3.3.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.13/dist-packages (from fvcore->pytorchvideo@ git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f->imagebind) (0.9.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub->timm->imagebind) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub->timm->imagebind) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub->timm->imagebind) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub->timm->imagebind) (26.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.0.0->imagebind) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->timm->imagebind) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->timm->imagebind) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->timm->imagebind) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->timm->imagebind) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub->timm->imagebind) (0.16.0)
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 6.0 MB/s eta 0:00:00
Downloading types_regex-2026.9.29.20261005-py3-none-any.whl (11 kB)
Downloading av-19.0.1-cp312-abi3-manylinux_2_28_x86_64.whl (35.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.0/35.0 MB 116.6 MB/s eta 0:00:00
Downloading parameterized-0.9.0-py2.py3-none-any.whl (20 kB)
Downloading portalocker-4.4.0-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.6/129.6 kB 18.4 MB/s eta 0:00:00
Downloading yacs-0.1.8-py3-none-any.whl (14 kB)
Building wheels for collected packages: imagebind, iopath, pytorchvideo, fvcore
  Building wheel for imagebind (setup.py) ... done
  Created wheel for imagebind: filename=imagebind-0.1.0-py3-none-any.whl size=1385668 sha256=9cbc24560a9d159b07cce4bd59c3a28d19402a4435a1e329593285f5c2d9822d
  Stored in directory: /tmp/pip-ephem-wheel-cache-g1li4zoa/wheels/df/9a/83/144b78c3ee619fef44402279f90654d97a8f88b0820a0e6513
  Building wheel for iopath (setup.py) ... done
  Created wheel for iopath: filename=iopath-0.1.10-py3-none-any.whl size=31596 sha256=4207f782f1e4ca3c6587fb97bee2c920d6c64f151ed00da617630068284ce43d
  Stored in directory: /root/.cache/pip/wheels/cd/c4/19/776124f304c8d9cb940cb164ec2ad635b42d9d1cf03217506d
  Building wheel for pytorchvideo (setup.py) ... done
  Created wheel for pytorchvideo: filename=pytorchvideo-0.1.5-py3-none-any.whl size=213083 sha256=26dc64dccc4be0850fd8f268fd9bef391f2caf73a4bb93437c60948b6e41c344
  Stored in directory: /root/.cache/pip/wheels/a9/5d/d8/e3fc0a70afd48b893197dc1e6381ea58655586cafadce384e5
  Building wheel for fvcore (setup.py) ... done
  Created wheel for fvcore: filename=fvcore-0.1.5.post20221221-py3-none-any.whl size=61447 sha256=18ae483e54262942bffdfb0ccb2bbf15cd5053b8eb2cc3995de9ea44bb13da09
  Stored in directory: /root/.cache/pip/wheels/6b/1b/9a/9f4843148961a522f56dbeaa5543071ac2389d9a079ec724ab
Successfully built imagebind iopath pytorchvideo fvcore
Installing collected packages: yacs, types-regex, portalocker, parameterized, ftfy, av, iopath, fvcore, pytorchvideo, imagebind
Successfully installed av-19.0.1 ftfy-6.3.1 fvcore-0.1.5.post20221221 imagebind-0.1.0 iopath-0.1.10 parameterized-0.9.0 portalocker-4.4.0 pytorchvideo-0.1.5 types-regex-2026.9.29.20261005 yacs-0.1.8
/bin/bash: line 1: 82: No such file or directory
Requirement already satisfied: torchcodec in /usr/local/lib/python3.13/dist-packages (0.11.0+cu130)

In [3]:
import torch
from imagebind.models.imagebind_model import ImageBindModel
from imagebind.models import imagebind_model
from imagebind import data
from imagebind.models.imagebind_model import ModalityType
import polars as pl
import random

/usr/local/lib/python3.13/dist-packages/imagebind/data.py:10: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [6]:
manifest_path = "drive/MyDrive/pokemon_data/manifest.jsonl"
device = "cuda:0" # "cpu", "cuda:0"

model = ImageBindModel(
    vision_embed_dim=1280,
    vision_num_blocks=32,
    vision_num_heads=16,
    text_embed_dim=1024,
    text_num_blocks=24,
    text_num_heads=16,
    out_embed_dim=1024,
    audio_drop_path=0.1,
    imu_drop_path=0.7,
)

In [4]:
#torch.cuda.get_device_name(0)

'NVIDIA RTX PRO 6000 Blackwell Server Edition'

In [7]:
model.load_state_dict(torch.load("drive/MyDrive/imagebind/.checkpoints/imagebind_huge.pth", weights_only=True))
model.eval()
model.to(device)

ImageBindModel(
  (modality_preprocessors): ModuleDict(
    (vision): RGBDTPreprocessor(
      (cls_token): tensor((1, 1, 1280), requires_grad=True)

      (rgbt_stem): PatchEmbedGeneric(
        (proj): Sequential(
          (0): PadIm2Video()
          (1): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
        )
      )
      (pos_embedding_helper): SpatioTemporalPosEmbeddingHelper(
        (pos_embed): tensor((1, 257, 1280), requires_grad=True)

      )
    )
    (text): TextPreprocessor(
      (pos_embed): tensor((1, 77, 1024), requires_grad=True)
      (mask): tensor((77, 77), requires_grad=False)

      (token_embedding): Embedding(49408, 1024)
    )
    (audio): AudioPreprocessor(
      (cls_token): tensor((1, 1, 768), requires_grad=True)

      (rgbt_stem): PatchEmbedGeneric(
        (proj): Conv2d(1, 768, kernel_size=(16, 16), stride=(10, 10), bias=False)
        (norm_layer): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
      (pos_embedding_helper): SpatioTemporalPosEmbeddingHelper(
        (pos_embed): tensor((1, 229, 768), requires_grad=True)

      )
    )
    (depth): RGBDTPreprocessor(
      (cls_token): tensor((1, 1, 384), requires_grad=True)

      (depth_stem): PatchEmbedGeneric(
        (proj): Conv2d(1, 384, kernel_size=(16, 16), stride=(16, 16), bias=False)
        (norm_layer): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      )
      (pos_embedding_helper): SpatioTemporalPosEmbeddingHelper(
        (pos_embed): tensor((1, 197, 384), requires_grad=True)

      )
    )
    (thermal): ThermalPreprocessor(
      (cls_token): tensor((1, 1, 768), requires_grad=True)

      (rgbt_stem): PatchEmbedGeneric(
        (proj): Conv2d(1, 768, kernel_size=(16, 16), stride=(16, 16), bias=False)
        (norm_layer): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      )
      (pos_embedding_helper): SpatioTemporalPosEmbeddingHelper(
        (pos_embed): tensor((1, 197, 768), requires_grad=True)

      )
    )
    (imu): IMUPreprocessor(
      (pos_embed): tensor((1, 251, 512), requires_grad=True)
      (cls_token): tensor((1, 1, 512), requires_grad=True)

      (imu_stem): PatchEmbedGeneric(
        (proj): Linear(in_features=48, out_features=512, bias=False)
        (norm_layer): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (modality_trunks): ModuleDict(
    (vision): SimpleTransformer(
      (pre_transformer_layer): Sequential(
        (0): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (1): EinOpsRearrange()
      )
      (blocks): Sequential(
        (0): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (1): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (2): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (3): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (4): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (5): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (6): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (7): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (8): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (9): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (10): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (11): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (12): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (13): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (14): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (15): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (16): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (17): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (18): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (19): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (20): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (21): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (22): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (23): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (24): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (25): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=1280, out_features=5120, bias=True)
            (act): GELU(approximate='none')
            (fc2): Linear(in_features=5120, out_features=1280, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
          (norm_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        )
        (26): BlockWithMasking(
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
          )
          (drop_path): Identity()
          (norm_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(

In [9]:
df = pl.read_ndjson(manifest_path)

use_image_flag = [True if i % 2 == 0 else False for i in range(df.shape[0])]
use_image_flag = random.sample(use_image_flag, len(use_image_flag))
df = df.with_columns(
    use_image=pl.Series(use_image_flag)
)

df

shape: (1_000, 6)
┌─────────┬──────────────┬────────────────────┬────────────────────┬───────────────────┬───────────┐
│ dex_num ┆ name         ┆ page_title         ┆ image_path         ┆ text              ┆ use_image │
│ ---     ┆ ---          ┆ ---                ┆ ---                ┆ ---               ┆ ---       │
│ str     ┆ str          ┆ str                ┆ str                ┆ str               ┆ bool      │
╞═════════╪══════════════╪════════════════════╪════════════════════╪═══════════════════╪═══════════╡
│ 0001    ┆ Bulbasaur    ┆ Bulbasaur          ┆ data/pokemon_data/ ┆ Bulbasaur is a    ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/0001_…      ┆ small, quadrupe…  ┆           │
│ 0002    ┆ Ivysaur      ┆ Ivysaur (Pokémon)  ┆ data/pokemon_data/ ┆ Ivysaur is a      ┆ false     │
│         ┆              ┆                    ┆ images/0002_…      ┆ quadrupedal       ┆           │
│         ┆              ┆                    ┆                    ┆ amphi…            ┆           │
│ 0003    ┆ Venusaur     ┆ Venusaur (Pokémon) ┆ data/pokemon_data/ ┆ Venusaur is a     ┆ false     │
│         ┆              ┆                    ┆ images/0003_…      ┆ squat, quadruped… ┆           │
│ 0004    ┆ Charmander   ┆ Charmander         ┆ data/pokemon_data/ ┆ Charmander is a   ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/0004_…      ┆ bipedal, repti…   ┆           │
│ 0005    ┆ Charmeleon   ┆ Charmeleon         ┆ data/pokemon_data/ ┆ Charmeleon is a   ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/0005_…      ┆ bipedal, repti…   ┆           │
│ …       ┆ …            ┆ …                  ┆ …                  ┆ …                 ┆ …         │
│ 1020    ┆ Gouging Fire ┆ Gouging Fire       ┆ data/pokemon_data/ ┆ Gouging Fire is a ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/1020_…      ┆ massive lion…     ┆           │
│ 1021    ┆ Raging Bolt  ┆ Raging Bolt        ┆ data/pokemon_data/ ┆ Raging Bolt is a  ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/1021_…      ┆ massive quadr…    ┆           │
│ 1022    ┆ Iron Boulder ┆ Iron Boulder       ┆ data/pokemon_data/ ┆ Iron Boulder is a ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/1022_…      ┆ spherical, b…     ┆           │
│ 1023    ┆ Iron Crown   ┆ Iron Crown         ┆ data/pokemon_data/ ┆ Iron Crown is an  ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/1023_…      ┆ armored turqu…    ┆           │
│ 1025    ┆ Pecharunt    ┆ Pecharunt          ┆ data/pokemon_data/ ┆ Pecharunt is a    ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/1025_…      ┆ small Pokémon r…  ┆           │
└─────────┴──────────────┴────────────────────┴────────────────────┴───────────────────┴───────────┘

In [10]:
image_df = df.filter(pl.col("use_image") == True)
text_df = df.filter(pl.col("use_image") == False)

images = ["drive/MyDrive/" + path[5:] for path in image_df["image_path"]]
text = text_df["text"]

images[0]

'drive/MyDrive/pokemon_data/images/0004_Charmander.png'

In [13]:
batch_size = 100

round = 0
all_embeddings = []
for i in range(0, len(images), batch_size):
    print("Round", round)
    cur_input = {
        ModalityType.VISION: data.load_and_transform_vision_data(images[i:i+batch_size], device),
        ModalityType.TEXT: data.load_and_transform_text(text[i:i+batch_size], device),
    }
    print("input loaded")

    with torch.amp.autocast(device, dtype=torch.float16):
        with torch.no_grad():
            embeddings = model(cur_input)

    print(embeddings)
    print()
    all_embeddings.append(embeddings)
    round += 1

Round 0
input loaded
{'vision': tensor([[ 0.0076,  0.0307,  0.0468,  ...,  0.0164,  0.0041,  0.0053],
        [ 0.0166,  0.0250,  0.0450,  ...,  0.0098,  0.0100, -0.0019],
        [ 0.0114,  0.0099,  0.0359,  ..., -0.0035, -0.0239,  0.0026],
        ...,
        [ 0.0118,  0.0097,  0.0546,  ...,  0.0083,  0.0128, -0.0010],
        [ 0.0352, -0.0026,  0.0430,  ..., -0.0018, -0.0100, -0.0127],
        [ 0.0046,  0.0251,  0.0486,  ..., -0.0193, -0.0113, -0.0100]],
       device='cuda:0'), 'text': tensor([[ 0.4888,  2.6005,  3.8929,  ...,  0.0635, -1.4891, -0.1580],
        [ 3.1548,  2.0426,  3.4702,  ...,  0.5220,  1.2801,  2.2151],
        [ 3.3492,  3.0044,  1.9368,  ..., -2.0400,  1.0907, -1.3537],
        ...,
        [ 0.9723, -2.9320, -1.8881,  ..., -0.1176,  4.6886,  2.0446],
        [-0.9563,  3.1725,  4.4278,  ..., -0.9422,  3.2412, -1.0328],
        [ 0.7165, -3.6554,  3.1763,  ..., -3.5652,  1.5247, -0.4920]],
       device='cuda:0')}

Round 1
input loaded
{'vision': tensor([[ 0.0031,  0.0268,  0.0609,  ...,  0.0338,  0.0139, -0.0127],
        [-0.0004,  0.0194,  0.0268,  ..., -0.0191, -0.0084,  0.0306],
        [-0.0089,  0.0283,  0.0621,  ..., -0.0020, -0.0216,  0.0004],
        ...,
        [ 0.0154, -0.0029,  0.0447,  ..., -0.0167,  0.0241, -0.0164],
        [ 0.0096,  0.0203,  0.0381,  ...,  0.0001,  0.0235, -0.0095],
        [ 0.0195,  0.0442,  0.0292,  ..., -0.0220, -0.0096,  0.0219]],
       device='cuda:0'), 'text': tensor([[-1.4952,  0.9074,  3.5971,  ..., -2.1393,  5.4494, -0.3864],
        [-1.6254,  1.6988,  0.4412,  ..., -1.2085,  0.1785, -0.9972],
        [-1.8884, -0.6445,  2.0637,  ..., -1.2038,  5.9040, -1.4267],
        ...,
        [ 2.1754,  4.1252,  2.8304,  ..., -4.5663,  0.6482, -0.4487],
        [ 0.7820,  0.5605,  0.9317,  ..., -0.1422,  0.4059,  0.5217],
        [-1.4397,  1.0223,  3.3578,  ..., -0.9706,  1.2345,  0.9282]],
       device='cuda:0')}

Round 2
input loaded
{'vision': tensor([[-0.0034, -0.0014,  0.0452,  ..., -0.0177,  0.0091,  0.0146],
        [ 0.0372, -0.0290,  0.0324,  ..., -0.0274,  0.0088, -0.0112],
        [ 0.0412, -0.0157,  0.0339,  ..., -0.0276, -0.0168,  0.0034],
        ...,
        [ 0.0222, -0.0304,  0.0588,  ..., -0.0184, -0.0107,  0.0119],
        [ 0.0418, -0.0219,  0.0470,  ..., -0.0260, -0.0185, -0.0041],
        [-0.0104, -0.0100,  0.0296,  ..., -0.0439, -0.0235,  0.0055]],
       device='cuda:0'), 'text': tensor([[ 0.7638,  1.5154,  3.9744,  ...,  0.9208,  5.9829, -1.9970],
        [-0.2437,  0.4932,  3.0853,  ...,  0.1844, -2.1869, -1.6208],
        [-0.6210,  1.8360,  4.2408,  ...,  0.4028,  4.4191, -0.9920],
        ...,
        [-2.8016,  3.2100,  2.6560,  ..., -0.6023,  7.5596, -2.1147],
        [ 0.5705,  2.9929,  2.4665,  ..., -1.3809,  3.9991,  4.5575],
        [-1.9266,  1.5945,  0.3369,  ..., -1.0379,  2.3376,  2.1330]],
       device='cuda:0')}

Round 3
input loaded
{'vision': tensor([[ 0.0005, -0.0266,  0.0475,  ...,  0.0182, -0.0017, -0.0162],
        [ 0.0264,  0.0118,  0.0630,  ..., -0.0184, -0.0103, -0.0261],
        [ 0.0251,  0.0187,  0.0182,  ..., -0.0157,  0.0016, -0.0157],
        ...,
        [ 0.0119, -0.0200,  0.0591,  ..., -0.0058, -0.0059, -0.0129],
        [ 0.0159, -0.0161,  0.0490,  ..., -0.0159, -0.0172,  0.0231],
        [ 0.0177, -0.0191,  0.0380,  ..., -0.0274, -0.0202,  0.0123]],
       device='cuda:0'), 'text': tensor([[-1.6328,  1.5070,  1.5395,  ..., -0.7056,  4.7484,  1.4195],
        [-0.6166,  0.9985,  5.3888,  ..., -2.6774,  3.5279,  2.1586],
        [ 0.4304,  0.6292, -1.8766,  ...,  0.3398,  3.1300, -0.3165],
        ...,
        [-1.9932,  2.0695,  4.1017,  ..., -2.7124,  3.3129, -0.0771],
        [-0.2446,  3.8080,  3.6702,  ...,  1.8688,  2.6166, -1.2498],
        [ 3.3262,  0.3073,  3.5788,  ..., -4.1660,  2.6456,  2.0551]],
       device='cuda:0')}

Round 4
input loaded
{'vision': tensor([[ 0.0146, -0.0220,  0.0597,  ..., -0.0234, -0.0419,  0.0120],
        [ 0.0299, -0.0099,  0.0129,  ..., -0.0183, -0.0338, -0.0112],
        [-0.0193,  0.0040,  0.0537,  ..., -0.0195, -0.0185,  0.0255],
        ...,
        [ 0.0039,  0.0026,  0.0309,  ..., -0.0114, -0.0262, -0.0070],
        [ 0.0285,  0.0006,  0.0400,  ..., -0.0382, -0.0189,  0.0072],
        [ 0.0258, -0.0092,  0.0456,  ..., -0.0019,  0.0006, -0.0014]],
       device='cuda:0'), 'text': tensor([[ 2.5724, -0.1439,  4.2166,  ..., -1.6929, -0.1430,  0.5385],
        [ 2.4750,  1.8218,  5.0780,  ..., -0.0356, -0.3350, -1.5428],
        [ 1.5538,  2.0139,  4.5866,  ..., -1.7730,  7.0277, -1.2928],
        ...,
        [ 2.7329,  6.2972, -1.8247,  ..., -1.6177,  2.8999, -0.8043],
        [ 1.1571,  1.4105,  3.5193,  ..., -2.1806, -1.6614,  1.8801],
        [-1.7530, -0.3431, -0.8610,  ...,  1.2768,  3.8981, -0.0689]],
       device='cuda:0')}

# Ingesting

In [14]:
!pip install lancedb

Collecting lancedb
  Downloading lancedb-0.40.0-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (7.5 kB)
Requirement already satisfied: deprecation>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from lancedb) (2.1.0)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.13/dist-packages (from lancedb) (2.1.3)
Requirement already satisfied: packaging>=23.0 in /usr/local/lib/python3.13/dist-packages (from lancedb) (26.3)
Requirement already satisfied: pyarrow>=16 in /usr/local/lib/python3.13/dist-packages (from lancedb) (23.0.1)
Requirement already satisfied: pydantic<3,>=2.7.4 in /usr/local/lib/python3.13/dist-packages (from lancedb) (2.13.5)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.13/dist-packages (from lancedb) (4.67.3)
Collecting lance-namespace>=0.3.2 (from lancedb)
  Downloading lance_namespace-0.13.0-py3-none-any.whl.metadata (1.6 kB)
Collecting lance-namespace-urllib3-client==0.13.0 (from lance-namespace>=0.3.2->lancedb)
  Downloading lance_namespace_urllib3_client-0.13.0-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from lance-namespace-urllib3-client==0.13.0->lance-namespace>=0.3.2->lancedb) (2.9.0.post0)
Requirement already satisfied: typing-extensions>=4.7.1 in /usr/local/lib/python3.13/dist-packages (from lance-namespace-urllib3-client==0.13.0->lance-namespace>=0.3.2->lancedb) (4.16.0)
Requirement already satisfied: urllib3<3.0.0,>=1.25.3 in /usr/local/lib/python3.13/dist-packages (from lance-namespace-urllib3-client==0.13.0->lance-namespace>=0.3.2->lancedb) (2.5.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2.7.4->lancedb) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2.7.4->lancedb) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2.7.4->lancedb) (0.4.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->lance-namespace-urllib3-client==0.13.0->lance-namespace>=0.3.2->lancedb) (1.17.0)
Downloading lancedb-0.40.0-cp310-abi3-manylinux_2_28_x86_64.whl (75.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.2/75.2 MB 43.4 MB/s eta 0:00:00
Downloading lance_namespace-0.13.0-py3-none-any.whl (13 kB)
Downloading lance_namespace_urllib3_client-0.13.0-py3-none-any.whl (406 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 406.8/406.8 kB 61.3 MB/s eta 0:00:00
Installing collected packages: lance-namespace-urllib3-client, lance-namespace, lancedb
Successfully installed lance-namespace-0.13.0 lance-namespace-urllib3-client-0.13.0 lancedb-0.40.0

In [21]:
all_embeddings[0]['vision'].shape

torch.Size([100, 1024])

In [23]:
all_embeddings[0]['vision'][0:2].shape

torch.Size([2, 1024])

In [16]:
image_df

shape: (500, 6)
┌─────────┬──────────────┬────────────────────┬────────────────────┬───────────────────┬───────────┐
│ dex_num ┆ name         ┆ page_title         ┆ image_path         ┆ text              ┆ use_image │
│ ---     ┆ ---          ┆ ---                ┆ ---                ┆ ---               ┆ ---       │
│ str     ┆ str          ┆ str                ┆ str                ┆ str               ┆ bool      │
╞═════════╪══════════════╪════════════════════╪════════════════════╪═══════════════════╪═══════════╡
│ 0004    ┆ Charmander   ┆ Charmander         ┆ data/pokemon_data/ ┆ Charmander is a   ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/0004_…      ┆ bipedal, repti…   ┆           │
│ 0006    ┆ Charizard    ┆ Charizard          ┆ data/pokemon_data/ ┆ Charizard is a    ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/0006_…      ┆ draconic , bipe…  ┆           │
│ 0012    ┆ Butterfree   ┆ Butterfree         ┆ data/pokemon_data/ ┆ Butterfree is a   ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/0012_…      ┆ lepidopteran i…   ┆           │
│ 0013    ┆ Weedle       ┆ Weedle (Pokémon)   ┆ data/pokemon_data/ ┆ Weedle is a       ┆ true      │
│         ┆              ┆                    ┆ images/0013_…      ┆ larval insect     ┆           │
│         ┆              ┆                    ┆                    ┆ Poké…             ┆           │
│ 0014    ┆ Kakuna       ┆ Kakuna (Pokémon)   ┆ data/pokemon_data/ ┆ Kakuna is a       ┆ true      │
│         ┆              ┆                    ┆ images/0014_…      ┆ yellow, insect    ┆           │
│         ┆              ┆                    ┆                    ┆ coc…              ┆           │
│ …       ┆ …            ┆ …                  ┆ …                  ┆ …                 ┆ …         │
│ 1010    ┆ Iron Leaves  ┆ Iron Leaves        ┆ data/pokemon_data/ ┆ Iron Leaves is a  ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/1010_…      ┆ mechanical Po…    ┆           │
│ 1012    ┆ Poltchageist ┆ Poltchageist       ┆ data/pokemon_data/ ┆ Poltchageist is a ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/1012_…      ┆ Pokémon made…     ┆           │
│ 1013    ┆ Sinistcha    ┆ Sinistcha          ┆ data/pokemon_data/ ┆ Sinistcha is a    ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/1013_…      ┆ Pokémon made of…  ┆           │
│ 1018    ┆ Archaludon   ┆ Archaludon         ┆ data/pokemon_data/ ┆ Archaludon is a   ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/1018_…      ┆ tall, metallic…   ┆           │
│ 1021    ┆ Raging Bolt  ┆ Raging Bolt        ┆ data/pokemon_data/ ┆ Raging Bolt is a  ┆ true      │
│         ┆              ┆ (Pokémon)          ┆ images/1021_…      ┆ massive quadr…    ┆           │
└─────────┴──────────────┴────────────────────┴────────────────────┴───────────────────┴───────────┘

In [46]:
text_df

shape: (500, 6)
┌─────────┬──────────────┬────────────────────┬────────────────────┬───────────────────┬───────────┐
│ dex_num ┆ name         ┆ page_title         ┆ image_path         ┆ text              ┆ use_image │
│ ---     ┆ ---          ┆ ---                ┆ ---                ┆ ---               ┆ ---       │
│ str     ┆ str          ┆ str                ┆ str                ┆ str               ┆ bool      │
╞═════════╪══════════════╪════════════════════╪════════════════════╪═══════════════════╪═══════════╡
│ 0001    ┆ Bulbasaur    ┆ Bulbasaur          ┆ data/pokemon_data/ ┆ Bulbasaur is a    ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/0001_…      ┆ small, quadrupe…  ┆           │
│ 0002    ┆ Ivysaur      ┆ Ivysaur (Pokémon)  ┆ data/pokemon_data/ ┆ Ivysaur is a      ┆ false     │
│         ┆              ┆                    ┆ images/0002_…      ┆ quadrupedal       ┆           │
│         ┆              ┆                    ┆                    ┆ amphi…            ┆           │
│ 0003    ┆ Venusaur     ┆ Venusaur (Pokémon) ┆ data/pokemon_data/ ┆ Venusaur is a     ┆ false     │
│         ┆              ┆                    ┆ images/0003_…      ┆ squat, quadruped… ┆           │
│ 0005    ┆ Charmeleon   ┆ Charmeleon         ┆ data/pokemon_data/ ┆ Charmeleon is a   ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/0005_…      ┆ bipedal, repti…   ┆           │
│ 0007    ┆ Squirtle     ┆ Squirtle (Pokémon) ┆ data/pokemon_data/ ┆ Squirtle is a     ┆ false     │
│         ┆              ┆                    ┆ images/0007_…      ┆ small reptilian … ┆           │
│ …       ┆ …            ┆ …                  ┆ …                  ┆ …                 ┆ …         │
│ 1019    ┆ Hydrapple    ┆ Hydrapple          ┆ data/pokemon_data/ ┆ Hydrapple is a    ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/1019_…      ┆ Pokémon compose…  ┆           │
│ 1020    ┆ Gouging Fire ┆ Gouging Fire       ┆ data/pokemon_data/ ┆ Gouging Fire is a ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/1020_…      ┆ massive lion…     ┆           │
│ 1022    ┆ Iron Boulder ┆ Iron Boulder       ┆ data/pokemon_data/ ┆ Iron Boulder is a ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/1022_…      ┆ spherical, b…     ┆           │
│ 1023    ┆ Iron Crown   ┆ Iron Crown         ┆ data/pokemon_data/ ┆ Iron Crown is an  ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/1023_…      ┆ armored turqu…    ┆           │
│ 1025    ┆ Pecharunt    ┆ Pecharunt          ┆ data/pokemon_data/ ┆ Pecharunt is a    ┆ false     │
│         ┆              ┆ (Pokémon)          ┆ images/1025_…      ┆ small Pokémon r…  ┆           │
└─────────┴──────────────┴────────────────────┴────────────────────┴───────────────────┴───────────┘

In [43]:
to_ingest = []

round = 0
for i in range(0, len(images), batch_size):
    print("Round", round)

    # vision set
    image_df_part = image_df.slice(i, i+batch_size).to_dict(as_series=False)
    vals = list(image_df_part.values()) + [all_embeddings[round]['vision'].tolist()]
    keys = list(image_df_part.keys()) + ["vector"]

    image_ingest = [dict(zip(keys, values)) for values in zip(*vals)]

    # text set
    text_df_part = text_df.slice(i, i+batch_size).to_dict(as_series=False)
    vals = list(text_df_part.values()) + [all_embeddings[round]['text'].tolist()]
    keys = list(text_df_part.keys()) + ["vector"]

    text_ingest = [dict(zip(keys, values)) for values in zip(*vals)]

    to_ingest += image_ingest + text_ingest
    round += 1

print(len(to_ingest))
to_ingest[0]

Round 0
Round 1
Round 2
Round 3
Round 4
1000

{'dex_num': '0004',
 'name': 'Charmander',
 'page_title': 'Charmander (Pokémon)',
 'image_path': 'data/pokemon_data/images/0004_Charmander.png',
 'text': "Charmander is a bipedal, reptilian Pokémon with a primarily orange body and blue eyes. Its underside from the chest down and the soles of its feet are cream-colored. It has two small fangs visible in its upper jaw and two smaller fangs in its lower jaw. A fire burns at the tip of this Pokémon's slender tail, which has blazed there since Charmander's birth.",
 'use_image': True,
 'vector': [0.0075536202639341354,
  0.030658485367894173,
  0.04675363749265671,
  0.028882469981908798,
  0.016439253464341164,
  0.045199621468782425,
  -0.02256651036441326,
  0.006338159088045359,
  0.0022408333607017994,
  0.05767613649368286,
  -0.015917548909783363,
  -0.007942124269902706,
  0.012543116696178913,
  0.0060051558539271355,
  0.004201389383524656,
  -0.0217451024800539,
  -0.009601589292287827,
  -0.00273340055719018,
  -0.030436484143137932,
  0.009279686957597733,
  0.02857166714966297,
  0.03267870470881462,
  -0.06047336384654045,
  0.01244321558624506,
  -0.024753231555223465,
  0.0007450944394804537,
  -0.020046787336468697,
  0.025397036224603653,
  -0.0056000021286308765,
  -0.02059069275856018,
  0.034499119967222214,
  -0.023820823058485985,
  0.05421290546655655,
  -0.012942721135914326,
  0.06455820053815842,
  0.009951243177056313,
  -0.039338767528533936,
  -0.012076912447810173,
  -0.0340995192527771,
  0.024753231555223465,
  -0.009912392124533653,
  -0.022289007902145386,
  0.0030580784659832716,
  0.02339901775121689,
  -0.037251945585012436,
  -0.008513779379427433,
  -0.021700702607631683,
  -0.09155365079641342,
  0.02506403438746929,
  -0.012942721135914326,
  0.0028069387190043926,
  0.026462646201252937,
  0.00846937857568264,
  -0.013986130245029926,
  -0.007475919555872679,
  -0.025463636964559555,
  0.003615858731791377,
  -0.023887421935796738,
  -0.007470369804650545,
  0.03509852662682533,
  0.013930629938840866,
  -0.007442619185894728,
  0.032212499529123306,
  0.04164758697152138,
  -0.009917942807078362,
  -0.017527064308524132,
  0.020579591393470764,
  -0.013042621314525604,
  -0.004398415796458721,
  0.03805115446448326,
  -0.010156595148146152,
  0.004983946681022644,
  0.03929436579346657,
  0.01603964902460575,
  -0.0556781180202961,
  0.05159328132867813,
  -0.00964599009603262,
  -0.009978992864489555,
  -0.011150053702294827,
  0.0012334990315139294,
  0.008447178639471531,
  0.019147679209709167,
  -0.010911401361227036,
  0.010162144899368286,
  0.010345296934247017,
  -0.008069775067269802,
  0.030192282050848007,
  -0.011988111771643162,
  0.003219030098989606,
  0.024020623415708542,
  0.010417447425425053,
  -0.04151438549160957,
  -0.04413401335477829,
  0.01850387267768383,
  -0.015695545822381973,
  0.01046739798039198,
  -0.03278970718383789,
  -0.029015671461820602,
  -0.008985533379018307,
  0.0017621414735913277,
  0.020768294110894203,
  -0.03452132269740105,
  -0.0160063486546278,
  0.015229341574013233,
  0.04573242738842964,
  0.06367019563913345,
  0.014574435539543629,
  0.01787116751074791,
  -0.009096534922719002,
  0.0066767120733857155,
  -0.012476515956223011,
  -0.0082473773509264,
  -0.010867001488804817,
  -0.006804363336414099,
  0.0035242829471826553,
  -0.018870176747441292,
  0.03942756727337837,
  0.028482865542173386,
  0.03432152047753334,
  0.003452132223173976,
  0.04626522958278656,
  -0.030236681923270226,
  -0.010583948343992233,
  0.00888008251786232,
  0.01619505137205124,
  0.0026015867479145527,
  0.0331227071583271,
  -0.004917345941066742,
  -0.005150448065251112,
  0.0038295357953757048,
  -0.024109425023198128,
  0.021123496815562248,
  0.014330233447253704,
  0.012909420765936375,
  -0.026684649288654327,
  0.02506403438746929,
  -0.0019855310674756765,
  0.03645274043083191,
  0.005416850559413433,
  -0.0085082296282053,
  -0.018847975879907608,
  0.02450902946293354,
  -0.0588749498128891,
  0.01809316873550415,
  -0.034232720732688904,
  -0.014874138869345188,
  -0.004587117582559586,
  0.019747084006667137,
  0.004229139536619186,
  -0.007414869032800198,
  0.006027356255799532,
  -0.0005626364727504551,
  0.013997230678796768,
  -0.00012695742771029472,
  -0.015240442007780075,
  0.021967105567455292,
  -0.024198224768042564,
  -0.010694949887692928,
  0.003721309592947364,
  0.025996442884206772,
  -0.025907641276717186,
  -0.007931023836135864,
  -0.001483251340687275,
  0.02044638991355896,
  0.009329636581242085,
  -0.011366506107151508,
  0.012509816326200962,
  -0.026063043624162674,
  0.0423801951110363,
  -0.002239445922896266,
  -0.010284245945513248,
  -0.016661254689097404,
  0.023754222318530083,
  0.015196042135357857,
  -0.01453003566712141,
  -0.011743909679353237,
  0.028815869241952896,
  0.0067100124433636665,
  -0.01671675592660904,
  -0.015218242071568966,
  0.005538951605558395,
  0.0047286441549658775,
  -0.0001718781713861972,
  0.009712590835988522,
  -0.01411933172494173,
  -0.04524402320384979,
  0.02712865360081196,
  -0.03862835839390755,
  -0.016705656424164772,
  -0.01891457661986351,
  0.04189179092645645,
  0.046620436012744904,
  0.016017450019717216,
  -0.0026529247406870127,
  0.01458553597331047,
  -0.009557189419865608,
  -0.004725869279354811,
  0.010644999332726002,
  0.011127853766083717,
  -0.012887219898402691,
  0.014208132401108742,
  -0.018403971567749977,
  -0.03552033007144928,
  0.021067995578050613,
  -0.016050750389695168,
  -0.0027778008952736855,
  0.016872156411409378,
  -0.01954728178679943,
  0.015118340961635113,
  -0.015395843423902988,
  -0.004870170261710882,
  0.012620817869901657,
  0.029903678223490715,
  0.007675721775740385,
  -0.007104066200554371,
  -0.024220425635576248,
  0.02033538930118084,
  0.004015462473034859,
  0.019036676734685898,
  0.013608726672828197,
  -0.10078894346952438,
  0.049417659640312195,
  0.011272154748439789,
  -0.030303282663226128,
  0.031146889552474022,
  -0.011588508263230324,
  -0.04622083157300949,
  -0.06380339711904526,
  0.02324361726641655,
  -0.04060417786240578,
  0.012587517499923706,
  0.028971269726753235,
  0.023665420711040497,
  -0.00469256890937686,
  -0.0021437075920403004,
  -0.011632908135652542,
  0.021478699520230293,
  8.589572098571807e-05,
  0.000886620779056102,
  -0.012631917372345924,
  0.03984937071800232,
  0.03629733994603157,
  -0.011299905367195606,
  -0.030503084883093834,
  -0.05119367688894272,
  -0.009967893362045288,
  -0.011410905979573727,
  0.0340329185128212,
  0.013353424146771431,
  0.02928207255899906,
  0.09901292622089386,
  0.008680281229317188,
  0.0015082266181707382,
  0.03285630792379379,
  -0.02959287539124489,
  -0.015007340349256992,
  0.017771266400814056,
  -0.0227552130818367,
  -0.021889403462409973,
  0.0018911801744252443,
  0.006143907085061073,
  -0.007059665862470865,
  -0.008669180795550346,
  -0.01148860715329647,
  -0.0012730431044474244,
  0.0030719535425305367,
  -0.0392499677836895,
  0.0052309236489236355,
  -0.00208959449082613,
  -0.01014549471437931,
  0.015273742377758026,
  -0.0014527260791510344,
  -0.019569482654333115,
  0.014918538741767406,
  0.010811501182615757,
  -0.0391833670437336,
  0.00397383701056242,
  0.012809519656002522,
  0.0005827554268762469,
  -0.033477913588285446,
  0.031324490904808044,
  -0.03447692096233368,
  -0.01828186959028244,
  0.021400999277830124,
  -0.02834966406226158,
  -0.0526144914329052,
  0.0074814697727561,
  0.05625532567501068,
  0.012165713123977184,
  -0.008774631656706333,
  0.05794253945350647,
  -0.002597424201667309,
  -0.015362543053925037,
  0.02977047674357891,
  0.0020590692292898893,
  0.003982162103056908,
  0.040382176637649536,
  -0.00306917866691947,
  -0.017660263925790787,
  -0.031213490292429924,
  -0.02308821491897106,
  -0.004420616198331118,
  0.02664024755358696,
  -0.06184977665543556,
  0.019946886226534843,
  -0.02763925865292549,
  -0.0022782962769269943,
  0.022033706307411194,
  0.03108029067516327,
  -0.030192282050848007,
  -0.022777412086725235,
  -0.017582563683390617,
  -0.011688409373164177,
  -0.047286439687013626,
  0.023931823670864105,
  -0.005194848403334618,
  0.007564720697700977,
  -0.010417447425425053,
  0.019092177972197533,
  0.011177804321050644,
  0.03509852662682533,
  -0.06668942421674728,
  -0.04839644953608513,
  -0.049417659640312195,
  -0.02055739238858223,
  -0.01615065149962902,
  -0.02701765112578869,
  0.002114569768309593,
  -0.01719406060874462,
  -0.0069486647844314575,
  0.002042419044300914,
  -0.04608763009309769,
  0.01104460284113884,
  0.03902796283364296,
  0.026285044848918915,
  0.016705656424164772,
  -0.00044226975296624005,
  -0.017416061833500862,
  -0.02548583783209324,
  0.02368762157857418,
  0.00578315369784832,
  -0.021389899775385857,
  0.0176047645509243,
  -0.030436484143137932,
  0.016949858516454697,
  -0.0003453172685112804,
  -0.043357003480196,
  -0.04209159314632416,
  0.020834894850850105,
  0.048440851271152496,
  0.023998424410820007,
  -0.006826563738286495,
  0.02439802698791027,
  -0.021800603717565536,
  0.0037573850713670254,
  0.0006261151866056025,
  -0.008036474697291851,
  -0.030414283275604248,
  0.011743909679353237,
  -0.024908632040023804,
  -0.026840049773454666,
  0.027261855080723763,
  0.008241826668381691,
  0.0025696740485727787,
  -0.03578673303127289,
  -0.0005192767130210996,
  -0.01888127624988556,
  0.02148980088531971,
  -0.009512788616120815,
  -0.04582122713327408,
  -0.018670374527573586,
  -0.02190050482749939,
  0.012054712511599064,
  -0.025308236479759216,
  -0.014752037823200226,
  0.04171418771147728,
  -0.0009226960828527808,
  -0.0016067399410530925,
  0.021989304572343826,
  -0.003746284870430827,
  -0.02279961295425892,
  0.10203215479850769,
  -0.06757742911577225,
  0.014430134557187557,
  -0.026884451508522034,
  0.10158814489841461,
  -0.014152632094919682,
  -0.02119009755551815,
  0.020768294110894203,
  0.03567573428153992,
  0.014374634250998497,
  0.03962736949324608,
  -0.0009906842606142163,
  0.020512990653514862,
  0.05217048525810242,
  0.010051143355667591,
  -0.024797631427645683,
  0.0008408328285440803,
  0.03163529559969902,
  -0.0057998038828372955,
  0.016472553834319115,
  0.027173053473234177,
  -0.00666006188839674,
  -0.008724681101739407,
  -0.011577407829463482,
  0.007503670174628496,
  0.039716169238090515,
  0.01014549471437931,
  0.0015623396029695868,
  -0.026618048548698425,
  0.015340343117713928,
  0.004986721556633711,
  -0.01581764779984951,
  -0.024975232779979706,
  0.012476515956223011,
  -0.03369991481304169,
  0.001011496875435114,
  -0.022710811346769333,
  0.0067488630302250385,
  0.019092177972197533,
  -0.015662245452404022,
  -0.0010364721529185772,
  -0.016095150262117386,
  0.009090985171496868,
  -0.06300418823957443,
  0.017038658261299133,
  0.007414869032800198,
  0.014308033511042595,
  -0.0038295357953757048,
  -0.017893366515636444,
  0.0024378602392971516,
  0.049417659640312195,
  -0.001680278219282627,
  0.02395402267575264,
  -0.090887650847435,
  -0.024753231555223465,
  0.0010780974989756942,
  -0.02899347059428692,
  -0.005436275620013475,
  0.004115363582968712,
  -0.014829738065600395,
  0.004156988579779863,
  -0.02272191271185875,
  0.003704659640789032,
  -0.015129441395401955,
  -0.012187913991510868,
  -0.03085828758776188,
  0.031990498304367065,
  0.0011773047735914588,
  0.015273742377758026,
  -0.019047778099775314,
  0.03059188462793827,
  0.002752825617790222,
  0.0141970319673419,
  0.022078106179833412,
  -0.006743312813341618,
  -0.004129238426685333,
  0.3988933265209198,
  -0.04302399978041649,
  0.029615076258778572,
  -0.02215580642223358,
  0.004112588241696358,
  0.026174044236540794,
  -0.04011577367782593,
  0.008091975003480911,
  -0.013741928152740002,
  0.04928445816040039,
  -0.013408925384283066,
  -0.012376615777611732,
  0.006149457301944494,
  0.01984698511660099,
  -0.013386724516749382,
  -0.0037129847332835197,
  0.009618239477276802,
  -0.016761155799031258,
  -0.06584581732749939,
  -0.003596433438360691,
  -0.05465690791606903,
  -0.0008401391096413136,
  -0.01712745986878872,
  -0.012509816326200962,
  0.006132807116955519,
  0.0037102096248418093,
  0.019802585244178772,
  0.05217048525810242,
  0.011988111771643162,
  -0.0026459870859980583,
  0.0031746295280754566,
  0.05669932812452316,
  -0.03929436579346657,
  -0.010861451737582684,
  0.010600598528981209,
  -0.011743909679353237,
  -0.01231001503765583,
  0.010384147055447102,
  -0.002164520090445876,
  -0.004312389995902777,
  0.011610708199441433,
  -0.016960958018898964,
  -0.04924006015062332,
  0.011011302471160889,
  -0.015806548297405243,
  -0.008685830980539322,
  -0.025041833519935608,
  0.05647732689976692,
  0.005344700068235397,
  -0.042180392891168594,
  0.0023032715544104576,
  0.0015415268717333674,
  0.06420300155878067,
  -0.051016077399253845,
  -0.012543116696178913,
  -0.0993681252002716,
  -0.01277621928602457,
  -0.002351834438741207,
  0.014152632094919682,
  0.018326271325349808,
  0.017993267625570297,
  -0.011743909679353237,
  -0.052880894392728806,
  -0.0012418241240084171,
  -0.017671365290880203,
  -0.02708425186574459,
  -0.014752037823200226,
  -0.0012001986615359783,
  0.017327262088656425,
  -0.015418043360114098,
  -0.009190885350108147,
  0.015273742377758026,
  0.008691380731761456,
  -0.008352828212082386,
  -0.010683849453926086,
  -0.05718773230910301,
  0.0008914770442061126,
  -0.0031468793749809265,
  0.007559170480817556,
  0.04435601457953453,
  0.01801546849310398,
  -0.022633111104369164,
  0.04455581679940224,
  -0.01285391952842474,
  0.022955013439059258,
  -0.11073463410139084,
  0.06606781482696533,
  -0.027284054085612297,
  -0.005275323987007141,
  -0.005228148773312569,
  -0.004340140614658594,
  -0.03365551307797432,
  0.039982572197914124,
  0.0038461859803646803,
  -0.0237320214509964,
  0.03134669363498688,
  0.035054128617048264,
  -0.03239010274410248,
  -0.013353424146771431,
  -0.008219626732170582,
  -0.007198417093604803,
  -0.03254550322890282,
  -0.03547593206167221,
  -0.011755009181797504,
  -0.02861606702208519,
  -0.009312986396253109,
  0.009052134118974209,
  -0.03212369978427887,
  0.008375028148293495,
  -0.02450902946293354,
  0.004526067059487104,
  -0.048485253006219864,
  0.01274291891604662,
  -0.02190050482749939,
  -0.013142522424459457,
  0.049151256680488586,
  -0.0065102106891572475,
  0.03574233502149582,
  0.01356432680040598,
  -0.03156869485974312,
  0.0007045096717774868,
  0.008696931414306164,
  0.017893366515636444,
  -0.014263632707297802,
  0.005369674880057573,
  -0.03085828758776188,
  0.06975305080413818,
  -0.011588508263230324,
  -0.03964956849813461,
  0.02570783905684948,
  -0.008708030916750431,
  -0.01063389889895916,
  -0.018559373915195465,
  0.008491579443216324,
  0.043667808175086975,
  -0.002318534068763256,
  -0.022300107404589653,
  0.006737763062119484,
  -0.004329040180891752,
  0.018592674285173416,
  -0.006943114567548037,
  -0.015806548297405243,
  -0.00835837796330452,
  0.000632012146525085,
  0.02708425186574459,
  0.009912392124533653,
  -0.04719763994216919,
  0.01899227686226368,
  -0.00556947709992528,
  -0.014308033511042595,
  -0.017593663185834885,
  -0.007359368726611137,
  -0.0022075329907238483,
  -0.005794254131615162,
  -0.04107038304209709,
  -0.021256698295474052,
  0.01067274995148182,
  0.017959967255592346,
  -0.05030566826462746,
  -0.008313977159559727,
  -0.0263072457164526,
  0.020834894850850105,
  0.02313261479139328,
  -0.01861487329006195,
  -0.011016853153705597,
  0.016894357278943062,
  0.017504863440990448,
  -0.011666208505630493,
  0.02439802698791027,
  0.013109222054481506,
  -0.016694555059075356,
  0.06233818084001541,
  0.03674134239554405,
  0.028682667762041092,
  -0.004939545877277851,
  0.004778594709932804,
  -0.0181264691054821,
  -0.023332417011260986,
  -0.030791686847805977,
  -0.07472589612007141,
  -0.01145530678331852,
  0.03425491973757744,
  0.009340737015008926,
  0.007781172636896372,
  0.04275760054588318,
  0.02834966406226158,
  0.03345571085810661,
  0.034299321472644806,
  -0.0537245012819767,
  0.06367019563913345,
  -0.03811775520443916,
  -0.06575701385736465,
  -0.013231323100626469,
  -0.020535191521048546,
  0.005122697912156582,
  0.02708425186574459,
  -0.004417841322720051,
  -0.011011302471160889,
  0.015284842811524868,
  0.026440447196364403,
  -0.0016164525877684355,
  0.0035381580237299204,
  0.010850351303815842,
  0.0496840626001358,
  0.03663033992052078,
  0.02066839300096035,
  -0.004523292183876038,
  -0.019680483266711235,
  0.03474332392215729,
  0.03183509781956673,
  -0.022477708756923676,
  -0.006554611027240753,
  0.013997230678796768,
  -0.005017246585339308,
  0.016738956794142723,
  -0.017527064308524132,
  0.011183354072272778,
  -0.006726662628352642,
  0.047552842646837234,
  0.013475526124238968,
  0.007459269370883703,
  0.01716076023876667,
  0.0226886123418808,
  -0.03656373918056488,
  0.024930832907557487,
  0.02592984214425087,
  0.041136983782052994,
  0.0537245012819767,
  -0.0007145691779442132,
  -0.006571261212229729,
  -0.024975232779979706,
  -0.0029165521264076233,
  -0.08431638777256012,
  -0.005119922570884228,
  -0.04413401335477829,
  0.014574435539543629,
  0.04213599115610123,
  0.008180776610970497,
  -0.019802585244178772,
  0.04062638059258461,
  0.019724883139133453,
  0.026884451508522034,
  0.026063043624162674,
  0.03920556604862213,
  0.007487019989639521,
  -0.009501688182353973,
  -0.023199215531349182,
  -0.0010441035265102983,
  0.0002965808962471783,
  0.017005357891321182,
  -0.021667402237653732,
  0.011177804321050644,
  -0.0023032715544104576,
  0.04291300103068352,
  0.004684243816882372,
  -0.013808528892695904,
  0.01283171959221363,
  0.0036352837923914194,
  3.575013761292212e-05,
  -0.022511009126901627,
  0.0007093659951351583,
  -0.005017246585339308,
  -0.006637861952185631,
  -0.004664818290621042,
  -0.02291061356663704,
  -0.019580582156777382,
  0.028815869241952896,
  -0.004398415796458721,
  0.02506403438746929,
  -0.04604322835803032,
  -0.02681785076856613,
  0.011599607765674591,
  0.04626522958278656,
  0.010422997176647186,
  0.011105653829872608,
  0.018847975879907608,
  0.031502094119787216,
  -0.011599607765674591,
  -0.017693564295768738,
  -0.05137128010392189,
  0.014740937389433384,
  0.0263738464564085,
  -0.008796831592917442,
  -0.021312199532985687,
  -0.0026848374400287867,
  -0.02313261479139328,
  -0.006943114567548037,
  0.030680686235427856,
  0.014296933077275753,
  -0.019502881914377213,
  0.04271319881081581,
  -0.01107790321111679,
  -0.0076590715907514095,
  -0.0050366721116006374,
  0.0014721512561663985,
  -0.0036602590698748827,
  -0.09244166314601898,
  -0.00374073488637805,
  -0.35218408703804016,
  0.011261055245995522,
  -0.0085082296282053,
  -0.006893164478242397,
  0.029637277126312256,
  -0.017704665660858154,
  0.05558931827545166,
  -0.024309227243065834,
  0.0320792980492115,
  -0.03356671333312988,
  -0.012665217742323875,
  -0.03081388771533966,
  -0.010972452349960804,
  0.010961351916193962,
  0.0015415268717333674,
  0.03678574413061142,
  -0.0012889995705336332,
  0.0038406357634812593,
  -0.024797631427645683,
  -0.023199215531349182,
  -0.014130432158708572,
  -0.003596433438360691,
  -0.007775622420012951,
  -0.010944701731204987,
  0.02052409201860428,
  -0.008752431720495224,
  -0.008558180183172226,
  -0.007475919555872679,
  -0.02249990962445736,
  0.006848763674497604,
  -0.011072353459894657,
  -0.00019789402722381055,
  0.03032548353075981,
  -0.021012496203184128,
  0.023332417011260986,
  0.059407755732536316,
  0.015085040591657162,
  0.006210507825016975,
  0.0016955408500507474,
  -0.0034632321912795305,
  -0.010012293234467506,
  0.007531420327723026,
  0.033788714557886124,
  -0.019636083394289017,
  0.022955013439059258,
  0.01505174022167921,

In [63]:
import lancedb

uri = "pokemon_db"
db = lancedb.connect(uri)

In [64]:
table = db.create_table("pokemon", data=to_ingest, mode="overwrite")

In [35]:
len(all_embeddings[0]['text'][0].tolist())

1024

In [70]:
query_vector = all_embeddings[0]['vision'][0].tolist()
#query_vector = all_embeddings[2]['text'][95].tolist()

result = (
    table.search(query_vector)
    .select(["name", "use_image", "_distance"])
    .limit(10)
    .to_polars()
)
print(result)

shape: (10, 3)
┌────────────┬───────────┬───────────┐
│ name       ┆ use_image ┆ _distance │
│ ---        ┆ ---       ┆ ---       │
│ str        ┆ bool      ┆ f32       │
╞════════════╪═══════════╪═══════════╡
│ Charmander ┆ true      ┆ 0.0       │
│ Charizard  ┆ true      ┆ 0.224603  │
│ Dragonite  ┆ true      ┆ 0.246567  │
│ Nidoqueen  ┆ true      ┆ 0.319709  │
│ Eevee      ┆ true      ┆ 0.354788  │
│ Salamence  ┆ true      ┆ 0.367259  │
│ Lickitung  ┆ true      ┆ 0.367272  │
│ Totodile   ┆ true      ┆ 0.371974  │
│ Quagsire   ┆ true      ┆ 0.38685   │
│ Mew        ┆ true      ┆ 0.390053  │
└────────────┴───────────┴───────────┘

In [49]:
#db.drop_table("pokemon")

# Querying

In [16]:
import lancedb

uri = "../../data/pokemon_db"
db = lancedb.connect(uri)

In [17]:
db.list_tables()

ListTablesResponse(context=None, tables=['pokemon'], page_token=None)

In [18]:
table = db.open_table("pokemon")

In [20]:
table.search().to_polars()

shape: (1_000, 7)
┌─────────┬──────────────┬───────────────┬───────────────┬──────────────┬───────────┬──────────────┐
│ dex_num ┆ name         ┆ page_title    ┆ image_path    ┆ text         ┆ use_image ┆ vector       │
│ ---     ┆ ---          ┆ ---           ┆ ---           ┆ ---          ┆ ---       ┆ ---          │
│ str     ┆ str          ┆ str           ┆ str           ┆ str          ┆ bool      ┆ array[f32,   │
│         ┆              ┆               ┆               ┆              ┆           ┆ 1024]        │
╞═════════╪══════════════╪═══════════════╪═══════════════╪══════════════╪═══════════╪══════════════╡
│ 0004    ┆ Charmander   ┆ Charmander    ┆ data/pokemon_ ┆ Charmander   ┆ true      ┆ [0.007554,   │
│         ┆              ┆ (Pokémon)     ┆ data/images/0 ┆ is a         ┆           ┆ 0.030658, …  │
│         ┆              ┆               ┆ 004_…         ┆ bipedal,     ┆           ┆ 0.0053]      │
│         ┆              ┆               ┆               ┆ repti…       ┆           ┆              │
│ 0006    ┆ Charizard    ┆ Charizard     ┆ data/pokemon_ ┆ Charizard is ┆ true      ┆ [0.016637,   │
│         ┆              ┆ (Pokémon)     ┆ data/images/0 ┆ a draconic , ┆           ┆ 0.02502, …   │
│         ┆              ┆               ┆ 006_…         ┆ bipe…        ┆           ┆ -0.0019]     │
│ 0012    ┆ Butterfree   ┆ Butterfree    ┆ data/pokemon_ ┆ Butterfree   ┆ true      ┆ [0.011366,   │
│         ┆              ┆ (Pokémon)     ┆ data/images/0 ┆ is a         ┆           ┆ 0.009898, …  │
│         ┆              ┆               ┆ 012_…         ┆ lepidopteran ┆           ┆ 0.00258…     │
│         ┆              ┆               ┆               ┆ i…           ┆           ┆              │
│ 0013    ┆ Weedle       ┆ Weedle        ┆ data/pokemon_ ┆ Weedle is a  ┆ true      ┆ [0.032541,   │
│         ┆              ┆ (Pokémon)     ┆ data/images/0 ┆ larval       ┆           ┆ 0.013124, …  │
│         ┆              ┆               ┆ 013_…         ┆ insect Poké… ┆           ┆ 0.00362…     │
│ 0014    ┆ Kakuna       ┆ Kakuna        ┆ data/pokemon_ ┆ Kakuna is a  ┆ true      ┆ [0.011231,   │
│         ┆              ┆ (Pokémon)     ┆ data/images/0 ┆ yellow,      ┆           ┆ 0.029003, …  │
│         ┆              ┆               ┆ 014_…         ┆ insect coc…  ┆           ┆ 0.00088…     │
│ …       ┆ …            ┆ …             ┆ …             ┆ …            ┆ …         ┆ …            │
│ 1019    ┆ Hydrapple    ┆ Hydrapple     ┆ data/pokemon_ ┆ Hydrapple is ┆ false     ┆ [-1.925704,  │
│         ┆              ┆ (Pokémon)     ┆ data/images/1 ┆ a Pokémon    ┆           ┆ -0.637682, … │
│         ┆              ┆               ┆ 019_…         ┆ compose…     ┆           ┆ 4.399…       │
│ 1020    ┆ Gouging Fire ┆ Gouging Fire  ┆ data/pokemon_ ┆ Gouging Fire ┆ false     ┆ [-1.295118,  │
│         ┆              ┆ (Pokémon)     ┆ data/images/1 ┆ is a massive ┆           ┆ 3.737894, …  │
│         ┆              ┆               ┆ 020_…         ┆ lion…        ┆           ┆ 2.2211…      │
│ 1022    ┆ Iron Boulder ┆ Iron Boulder  ┆ data/pokemon_ ┆ Iron Boulder ┆ false     ┆ [2.732905,   │
│         ┆              ┆ (Pokémon)     ┆ data/images/1 ┆ is a         ┆           ┆ 6.297201, …  │
│         ┆              ┆               ┆ 022_…         ┆ spherical,   ┆           ┆ -0.8042…     │
│         ┆              ┆               ┆               ┆ b…           ┆           ┆              │
│ 1023    ┆ Iron Crown   ┆ Iron Crown    ┆ data/pokemon_ ┆ Iron Crown   ┆ false     ┆ [1.157139,   │
│         ┆              ┆ (Pokémon)     ┆ data/images/1 ┆ is an        ┆           ┆ 1.410521, …  │
│         ┆              ┆               ┆ 023_…         ┆ armored      ┆           ┆ 1.88014…     │
│         ┆              ┆               ┆               ┆ turqu…       ┆           ┆              │
│ 1025    ┆ Pecharunt    ┆ Pecharunt     ┆ data/pokemon_ ┆ Pecharunt is ┆ false     ┆ [-1.75301,   │
│         ┆              ┆ (Pokémon)     ┆ data/images/1 ┆ a small      ┆           ┆ -0.343087, … │
│         ┆              ┆               ┆ 025_…         ┆ Pokémon r…   ┆           ┆ -0.068…      │
└─────────┴──────────────┴───────────────┴───────────────┴──────────────┴───────────┴──────────────┘

In [ ]:
# Example Query

query_vector = all_embeddings[0]['vision'][0].tolist()
#query_vector = all_embeddings[2]['text'][95].tolist()

result = (
    table.search(query_vector)
    .select(["name", "use_image", "_distance"])
    .limit(10)
    .to_polars()
)
print(result)